table 'Active Students DSET'
	lineageTag: 31e67b19-92a2-463a-8d63-187ddc09cb46

	measure 'This Time Last Year' = ```
			
			VAR PreviousYearStartDate = DATE(YEAR(TODAY()) - 1, 1, 1)
			VAR PreviousYearEndDate = DATE(YEAR(TODAY()) - 1, 12, 31)
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]),
			        FILTER(
			            'Active Students DSET',
			            'Active Students DSET'[STPR_START_DATE] >= PreviousYearStartDate &&
			            'Active Students DSET'[STPR_START_DATE] <= PreviousYearEndDate
			        )
			    )
			
			```
		formatString: 0
		lineageTag: 86bdc8a6-c5fb-4868-b3a2-7a553879771e

	measure 'Current - Last year active Students' = ```
			
			var Overall = CALCULATE(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]))
			Var previousYr = DISTINCTCOUNT('Active Students LY'[STUDENT_PROGRAMS_ID])
			var varian = Overall - previousYr 
			RETURN
			//varian/Overall
			 IF(
			        DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]) > DISTINCTCOUNT('Active Students LY'[STUDENT_PROGRAMS_ID]),             
			        CONCATENATE("+", FORMAT(DIVIDE(varian,previousYr,0), "0.00%")),      
			        CONCATENATE("-", FORMAT(ABS(DIVIDE(varian,previousYr,0)), "0.00%"))   
			    )
			```
		lineageTag: f1997cd2-8639-4bb0-ab66-e70f55bf3479

	measure Flag1 =
			IF(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]) > DISTINCTCOUNT('Active Students LY'[STUDENT_ID]), UNICHAR(9650), UNICHAR(9660))
			
			// "🔺","🔻")
		lineageTag: c271b895-60fa-434d-8032-b5f6a4fc9ac1

	measure CurrentTerm! = ```
			
			CALCULATE(DISTINCTCOUNT('Active Students DSET'[STUDENT_PROGRAMS_ID]),DIM_Terms[TERM_END_DATE]>= TODAY() && DIM_Terms[TERM_START_DATE] <= TODAY() )
			
			```
		formatString: 0
		lineageTag: e57e3f12-84da-444e-a06b-d989c95d8e52

	measure Active_students_LY_Flag1 =
			IF(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]) > DISTINCTCOUNT('Active Students LY'[STUDENT_ID]), "#00B050", "#C81515")
			
			// "🔺","🔻")
		lineageTag: 6849ea09-cacb-4b58-bc0f-8b1185485dc3

	measure FirstGenCY = ```
			
			VAR TotalStudents = CALCULATE(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]),KEEPFILTERS('Active Students DSET'[FIRST_GEN_CHECK]<>BLANK()))
			VAR FirstGenStudents = CALCULATE(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]),'Active Students DSET'[FIRST_GEN_CHECK]="Y")
			RETURN
			DIVIDE(FirstGenStudents,TotalStudents,0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fd793b1c-1e82-4012-adf1-f92c84514b07

	measure 'Student Count' = DISTINCTCOUNT('Active Students DSET'[STUDENT_ID])+DISTINCTCOUNT('Active Students LY'[STUDENT_ID])+DISTINCTCOUNT('Active Students 2Y'[STUDENT_ID])
		formatString: 0
		lineageTag: 781d6b71-e019-4b1a-8c0e-ff522174dd92

	measure RacePercentage = DIVIDE([Student Count],CALCULATE([Student Count],ALLSELECTED('DIM_Ethnicity')))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 56853c20-7504-4b52-a5e5-151537485d70

	measure STUDENT_ID_COUNT =
			
			VAR STUDENT = CALCULATE(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]))
			RETURN
			IF(STUDENT= BLANK(),0,STUDENT)
		formatString: #,0
		lineageTag: 2145fae8-0d28-418b-ae00-e5f7b472857b

	measure ActiveFontColor1 = ```
			
			IF(
			DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]) < DISTINCTCOUNT('Active Students LY'[STUDENT_ID]) || 
			DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]) < [Current_Month_Budget],
			    "#C00000",   -- dark red
			    "#000000"    -- default black
			)
			
			```
		lineageTag: 416af320-3b56-4be8-bc41-7c17f52361ee

	column STUDENT_ID
		dataType: string
		lineageTag: fdb39c36-9ace-4723-b2b6-8047e42ec114
		summarizeBy: none
		sourceColumn: STUDENT_ID

		annotation SummarizationSetBy = Automatic

	column PROGRAM_ID
		dataType: string
		lineageTag: 9c4d714b-5382-4cce-915e-5e2cc06ba34f
		summarizeBy: none
		sourceColumn: PROGRAM_ID

		annotation SummarizationSetBy = Automatic

	column MOST_RECENT_PROGRAM
		dataType: int64
		formatString: 0
		lineageTag: 215a3e2b-8d9d-42f9-ac1a-4b92091864ae
		summarizeBy: sum
		sourceColumn: MOST_RECENT_PROGRAM

		annotation SummarizationSetBy = Automatic

	column STUDENT_PROGRAMS_ID
		dataType: string
		lineageTag: 763ecced-a1e5-48b5-aaf1-02a3f5f2e5d5
		summarizeBy: none
		sourceColumn: STUDENT_PROGRAMS_ID

		annotation SummarizationSetBy = Automatic

	column STPR_LOCATION
		dataType: string
		lineageTag: b3d9a48c-1a1e-4407-aa6c-7fad91400809
		summarizeBy: none
		sourceColumn: STPR_LOCATION

		annotation SummarizationSetBy = Automatic

	column STPR_ADMIT_STATUS
		dataType: string
		lineageTag: c0e93a2d-2782-447a-8fa6-63c45bcd47b1
		summarizeBy: none
		sourceColumn: STPR_ADMIT_STATUS

		annotation SummarizationSetBy = Automatic

	column STPR_STATUS
		dataType: string
		lineageTag: 4a6b4113-7015-4303-8e76-0ef2acf11b9e
		summarizeBy: none
		sourceColumn: STPR_STATUS

		annotation SummarizationSetBy = Automatic

	column STPR_STATUS_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 733212e1-2e32-4a2a-bee3-a18738f253be
		summarizeBy: none
		sourceColumn: STPR_STATUS_DATE

		variation Variation
			isDefault
			relationship: 5e4e3647-faae-4160-aa0e-0a11062c1b6e
			defaultHierarchy: LocalDateTable_2c4aee8d-88d8-4c3a-ae68-50330b497c96.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STPR_START_DATE
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: 7ea2f495-bdae-45da-9067-abb7a553bc92
		summarizeBy: none
		sourceColumn: STPR_START_DATE

		variation Variation
			isDefault
			relationship: b94e0d00-8461-43b5-866f-d2b725899de8
			defaultHierarchy: LocalDateTable_db369724-dbd8-4ad7-b3db-937ab140818d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column STPR_END_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: c9775306-7da0-44cc-a51a-3223f964cf89
		summarizeBy: none
		sourceColumn: STPR_END_DATE

		variation Variation
			isDefault
			relationship: 74836c2e-5411-4cca-936a-b1521598f1b0
			defaultHierarchy: LocalDateTable_881d7106-b7a0-4c84-b143-0cb5dc9e6386.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ProgramStatus
		dataType: string
		lineageTag: 701f2ab2-2429-4610-a470-087412f3beb7
		summarizeBy: none
		sourceColumn: ProgramStatus

		annotation SummarizationSetBy = Automatic

	column LOC_DESC
		dataType: string
		lineageTag: 8ea5e38a-4bad-45e0-b0cf-1aa8fb3d881f
		summarizeBy: none
		sourceColumn: LOC_DESC

		annotation SummarizationSetBy = Automatic

	column FIRST_NAME
		dataType: string
		lineageTag: c3103998-0284-452f-b10b-bea1aa89551f
		summarizeBy: none
		sourceColumn: FIRST_NAME

		annotation SummarizationSetBy = Automatic

	column LAST_NAME
		dataType: string
		lineageTag: a525898e-c933-4cc7-a574-e036a03ba5cd
		summarizeBy: none
		sourceColumn: LAST_NAME

		annotation SummarizationSetBy = Automatic

	column AdmissionStatus
		dataType: string
		lineageTag: 20c27b55-dec1-47ce-b180-53f177e1258d
		summarizeBy: none
		sourceColumn: AdmissionStatus

		annotation SummarizationSetBy = Automatic

	column ReportDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: fc214dfc-affb-433f-ac91-c79bfd7067c1
		summarizeBy: none
		sourceColumn: ReportDate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 741e6526-eb77-4810-b560-da30515a6223
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: bd3edc7e-931e-44b2-996b-3390d76de6fa
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column FIRST_GEN_CHECK
		dataType: string
		lineageTag: 70f8fb9e-e5cd-42b5-b2b2-dac22c0e72c2
		summarizeBy: none
		sourceColumn: FIRST_GEN_CHECK

		annotation SummarizationSetBy = Automatic

	column GENDER
		dataType: string
		lineageTag: 52cb39fe-3a2e-431e-9119-531df28d3218
		summarizeBy: none
		sourceColumn: GENDER

		annotation SummarizationSetBy = Automatic

	column IPEDSEthnicity
		dataType: string
		lineageTag: 5d95a8e7-e68f-474a-bfd9-db667204466c
		summarizeBy: none
		sourceColumn: IPEDSEthnicity

		annotation SummarizationSetBy = Automatic

	partition 'Active Students DSET' = m
		mode: import
		queryGroup: Students
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "coll18_repl_production", [Query="WITH StudentProgram#(lf)AS (#(lf)#(tab)SELECT LEFT(SP.STUDENT_PROGRAMS_ID, 7) STUDENT_ID#(lf)#(tab)#(tab),RIGHT(SP.STUDENT_PROGRAMS_ID, LEN(SP.STUDENT_PROGRAMS_ID) - 8) PROGRAM_ID#(lf)#(tab)#(tab),ROW_NUMBER() OVER (#(lf)#(tab)#(tab)#(tab)PARTITION BY LEFT(SP.STUDENT_PROGRAMS_ID, 7) ORDER BY D.STPR_START_DATE DESC#(lf)#(tab)#(tab)#(tab)) MOST_RECENT_PROGRAM#(lf)#(tab)#(tab),SP.STUDENT_PROGRAMS_ID#(lf)#(tab)#(tab),SP.STPR_LOCATION#(lf)#(tab)#(tab),SP.STPR_ADMIT_STATUS#(lf)#(tab)#(tab),SPS.STPR_STATUS#(lf)#(tab)#(tab),SPS.STPR_STATUS_DATE#(lf)#(tab)#(tab),D.STPR_START_DATE#(lf)#(tab)#(tab),D.STPR_END_DATE#(lf)#(tab)#(tab),V.VAL_EXTERNAL_REPRESENTATION ProgramStatus#(lf)#(tab)#(tab),A.ADMS_DESC AdmissionStatus#(lf)#(tab)FROM STUDENT_PROGRAMS SP#(lf)#(tab)LEFT JOIN STPR_DATES D ON SP.STUDENT_PROGRAMS_ID = D.STUDENT_PROGRAMS_ID#(lf)#(tab)#(tab)AND D.POS = 1#(lf)#(tab)LEFT JOIN STPR_STATUSES SPS ON SP.STUDENT_PROGRAMS_ID = SPS.STUDENT_PROGRAMS_ID#(lf)#(tab)#(tab)AND SPS.POS = 1#(lf)#(tab)LEFT JOIN VALS V ON SPS.STPR_STATUS = V.VAL_INTERNAL_CODE#(lf)#(tab)#(tab)AND V.VALCODE_ID = 'STUDENT.PROGRAM.STATUSES'#(lf)#(tab)LEFT JOIN ADMIT_STATUSES A ON SP.STPR_ADMIT_STATUS = A.ADMIT_STATUSES_ID#(lf)#(tab)WHERE 1 = 1#(lf)#(tab)),#(lf)#(tab)ACCEPTABLE_TERMS AS#(lf)#(tab)(#(lf)#(tab)#(tab)SELECT CASE WHEN GETDATE() BETWEEN CT.TERM_START_DATE AND CT.TERM_END_DATE#(lf)#(tab)#(tab)THEN CT.TERMS_ID#(lf)#(tab)#(tab)ELSE PT.PREV_TERM END TERM_TO_BE_USED#(lf)#(tab)#(tab)FROM TERMS CT#(lf)#(tab)#(tab)INNER JOIN (#(lf)#(tab)#(tab)#(tab)SELECT  TERMS_ID,#(lf)#(tab)#(tab)#(tab)LAG(TERMS_ID) OVER (ORDER BY TERM_START_DATE) PREV_TERM, #(lf)#(tab)#(tab)#(tab) LAG(TERM_END_DATE) OVER (ORDER BY TERM_START_DATE) PREV_END_DATE#(lf)#(tab)#(tab)#(tab)FROM TERMS#(lf)#(tab)#(tab)#(tab)WHERE RIGHT(TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)#(tab)#(tab))PT ON CT.TERMS_ID = PT.TERMS_ID#(lf)#(tab)#(tab)WHERE RIGHT(CT.TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)AND GETDATE() BETWEEN PT.PREV_END_DATE AND CT.TERM_END_DATE#(lf)#(tab)#(tab)UNION#(lf)#(tab)#(tab)SELECT TERMS_ID TERM_TO_BE_USED#(lf)#(tab)#(tab)FROM TERMS#(lf)#(tab)#(tab)WHERE GETDATE() BETWEEN TERM_START_DATE AND TERM_END_DATE#(lf)#(tab)),#(lf)#(tab)#(lf)ENROLLED_IN_CLASS AS (#(lf)#(tab)SELECT DISTINCT SCS_STUDENT #(lf)#(tab)FROM STUDENT_COURSE_SEC SCS#(lf)#(tab)INNER JOIN STC_STATUSES STC ON SCS.SCS_STUDENT_ACAD_CRED = STC.STUDENT_ACAD_CRED_ID AND STC.POS = 1#(lf)#(tab)INNER JOIN COURSE_SECTIONS CS ON SCS.SCS_COURSE_SECTION = CS.COURSE_SECTIONS_ID#(lf)#(tab)INNER JOIN ACCEPTABLE_TERMS T ON CS.SEC_TERM = T.TERM_TO_BE_USED#(lf)#(tab)WHERE STC.STC_STATUS IN ('A','N')#(lf)),#(lf)Ethnicity AS (SELECT DISTINCT STUDENT_ID, IPEDS_RACE_ETHNIC_DESC #(lf)FROM STUDENT_ACAD_PROGRAMS_VIEW WITH (NOLOCK))#(lf)#(lf)SELECT SP.*, L.LOC_DESC, P.FIRST_NAME, P.LAST_NAME, GETDATE() ReportDate, YEAR(GETDATE()) Year,DATEDIFF(yy, P.BIRTH_DATE, GETDATE()) Age, P.GENDER, E.IPEDS_RACE_ETHNIC_DESC #(lf)FROM StudentProgram SP#(lf)LEFT JOIN LOCATIONS L ON SP.STPR_LOCATION = L.LOCATIONS_ID#(lf)INNER JOIN PERSON P ON SP.STUDENT_ID = P.ID#(lf)INNER JOIN ENROLLED_IN_CLASS EIC ON SP.STUDENT_ID = EIC.SCS_STUDENT#(lf)LEFT JOIN Ethnicity E ON E.STUDENT_ID = SP.STUDENT_ID#(lf)WHERE STPR_STATUS = 'A'#(lf)AND STPR_START_DATE <= GETDATE()#(lf)--AND PROGRAM_ID IN (@program)#(lf)--AND STPR_LOCATION IN (@campus)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ReportDate", type date}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"STUDENT_ID"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"STUDENT_ID"}, Diversity_FirstGen, {"studentId"}, "Diversity_FirstGen", JoinKind.LeftOuter),
				    #"Expanded Diversity_FirstGen" = Table.ExpandTableColumn(#"Merged Queries", "Diversity_FirstGen", {"FIRST_GEN_CHECK"}, {"FIRST_GEN_CHECK"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Diversity_FirstGen",null,"N/A",Replacer.ReplaceValue,{"GENDER"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"IPEDS_RACE_ETHNIC_DESC", "IPEDSEthnicity"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

