table 'Dim Recommend Galen'
	lineageTag: bbeb9bab-fc41-4020-bc85-5fb61a6400e8

	measure CY_QTR = ```
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			 CALCULATE(FORMAT([Response_CYQTR], "#,0")& " ("& FORMAT([Response_CYQTR%], "0.0%"&")"),ALLSELECTED()),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",CALCULATE(FORMAT([Surveyed_CYQTR_FInal], "#,0"),ALLSELECTED()),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([ResponseID_count_QTR], "#,0") & " "& FORMAT([Recommand_CYQTR%], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([ResponseID_count_QTR], "#,0") & " "& FORMAT([Recommand_CYQTR%], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([ResponseID_count_QTR], "#,0") & " "& FORMAT([Recommand_CYQTR%], "0.0%"))))))
			```
		lineageTag: 34ed3a47-c9f5-46b6-b44c-08ac79325df4

	measure CY_YTD = ```
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			 CALCULATE( FORMAT([Response_CYTD], "#,0")& " ("& FORMAT([Response_CYTD%], "0.0%") & ")",ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",CALCULATE(FORMAT([Surveyed_CYTD_FInal], "#,0"),ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([ResponseID_count_YTD], "#,0") & " "& FORMAT([Recommand_CYTD%], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([ResponseID_count_YTD], "#,0") & " "& FORMAT([Recommand_CYTD%], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([ResponseID_count_YTD], "#,0") & " "& FORMAT([Recommand_CYTD%], "0.0%"))))))
			
			```
		lineageTag: 722508fd-76d1-4c4d-b791-d68acbbd32fa

	measure LY_QTR = ```
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			 CALCULATE( FORMAT([Response_Count_LYQTR], "#,0")& " ("& FORMAT([Response_LYQTR%], "0.0%"&")"),ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",CALCULATE(FORMAT([Surveyed_LYQTR_FInal], "#,0"),ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([Response_Count_LYQTR], "#,0")  & " "& FORMAT([Recommand_LYQTR%], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([Response_Count_LYQTR], "#,0")  & " "& FORMAT([Recommand_LYQTR%], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([Response_Count_LYQTR], "#,0")  & " "& FORMAT([Recommand_LYQTR%], "0.0%"))))))
			```
		lineageTag: 2785acee-7141-4818-884c-8d33a586056d

	measure LY_YTD = ```
			
			var C_Response_Count_LYTD = CALCULATE(COUNT('FACT_Satisfaction >2024'[ResponseId]),DIM_Terms[LastYearYTDFlag]=1)+0
			var C_Surveyed_LYTD_Final=COALESCE(
			    SUMX(
			        VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			        [Enrolled_LYTD]
			    ),
			    0
			)
			
			return 
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			 CALCULATE( COALESCE(FORMAT([Response_count_LYTD], "#,0")& " ("& FORMAT([Response_LYTD%], "0.0%") & ")",
			 FORMAT(C_Response_Count_LYTD, "#,0")& " ("& FORMAT([Response_LYTD%], "0.0%") & ")")
			 ,ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",CALCULATE(COALESCE(FORMAT([Surveyed_LYTD_Final], "#,0"),FORMAT(C_Surveyed_LYTD_Final, "#,0")),
			 ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",COALESCE(FORMAT([Response_Count_LYTD], "#,0") & " "& FORMAT([Recommand_LYTD%], "0.0%"),
			 FORMAT(C_Response_Count_LYTD, "#,0") & " "& FORMAT([c_Recommand_LYTD%], "0.0%")),
			 
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",COALESCE(FORMAT([Response_Count_LYTD], "#,0") & " "& FORMAT([Recommand_LYTD%], "0.0%"),
			 FORMAT(C_Response_Count_LYTD, "#,0") & " "& FORMAT([c_Recommand_LYTD%], "0.0%")),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",COALESCE(FORMAT([Response_Count_LYTD], "#,0") & " "& FORMAT([Recommand_LYTD%], "0.0%"),
			 FORMAT(C_Response_Count_LYTD, "#,0") & " "& FORMAT([c_Recommand_LYTD%], "0.0%")))))))
			```
		lineageTag: cf590e31-d216-48f5-acbc-988fdbb53388

	measure 'QTR to QTR1' = ```
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			 CALCULATE( FORMAT([CYQTR-LYQTR_variance], "0.00%"),ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",BLANK(),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([QTR to QTR], "0.00%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([QTR to QTR], "0.00%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([QTR to QTR], "0.00%"))))))
			```
		lineageTag: b41d3f82-155c-497d-a42d-7069c3414952

	measure 'YTD to YTD1' = ```
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			 CALCULATE( FORMAT([CYTD-LYTD_variance], "0.0%"),ALLSELECTED()),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",BLANK(),
			
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([YTD to YTD], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([YTD to YTD], "0.0%"),
			 if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([YTD to YTD], "0.0%"))))))
			```
		lineageTag: 0a3081f3-7ee0-4036-a0ec-68b4e09c74c4

	measure LY_QTR_2024_ON = ```
			
			
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "RESPONDED",
			CALCULATE(COALESCE(FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " (" & FORMAT([Response_LYQTR%_2024_ON], "0.0%") & ")",
			    FORMAT([Response_Count_LYQTR], "#,0") & " (" & FORMAT([Response_LYQTR%], "0.0%") & ")")
			,
			ALLSELECTED()),
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "SURVEYED",
			CALCULATE(COALESCE(FORMAT([Surveyed_LYQTR_FInal_2024_ON], "#,0"),
			    FORMAT([Surveyed_LYQTR_FInal], "#,0")
			),ALLSELECTED()),
			         
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Yes",
			COALESCE(
			FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			FORMAT([Response_Count_LYQTR], "#,0") & " " & FORMAT([Recommand_LYQTR%], "0.0%")),
			// FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%")),
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "No",
			COALESCE(
			    FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			FORMAT([Response_Count_LYQTR], "#,0") & " " & FORMAT([Recommand_LYQTR%], "0.0%")),
			//FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%")),
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Unknown",
			COALESCE(FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			    FORMAT([Response_Count_LYQTR], "#,0") & " " & FORMAT([Recommand_LYQTR%], "0.0%")))))))
			//FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%")))))))
			
			
			// IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "RESPONDED",
			// CALCULATE(COALESCE(FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " (" & FORMAT([Response_LYQTR%_2024_ON], "0.0%") & ")", 
			// FORMAT([Response_Count_LYQTR], "#,0") & " (" & FORMAT([Response_LYQTR%], "0.0%") & ")"),
			// ALLSELECTED()),
			
			// IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "SURVEYED",
			// CALCULATE(COALESCE(FORMAT([Surveyed_LYQTR_FInal_2024_ON], "#,0"), 
			// FORMAT([Surveyed_LYQTR_FInal], "#,0")),ALLSELECTED()),
			         
			// IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Yes",
			// COALESCE(
			// FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			// FORMAT([Response_Count_LYQTR], "#,0") & " " & FORMAT([Recommand_LYQTR%], "0.0%")),
			
			// IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "No",
			// COALESCE(
			// FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			// FORMAT([Response_Count_LYQTR], "#,0") & " " & FORMAT([Recommand_LYQTR%], "0.0%")),
			
			// IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Unknown",
			// COALESCE(FORMAT([Response_Count_LYQTR_2024_ON], "#,0") & " " & FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			// FORMAT([Response_Count_LYQTR], "#,0") & " " & FORMAT([Recommand_LYQTR%], "0.0%")))))))
			
			
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			//  CALCULATE( FORMAT([Response_Count_LYQTR_2024_ON], "#,0")& " ("& FORMAT([Response_LYQTR%_2024_ON], "0.0%"&")"),ALLSELECTED()),
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",CALCULATE(FORMAT([Surveyed_LYQTR_FInal_2024_ON], "#,0"),ALLSELECTED()),
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([Response_Count_LYQTR_2024_ON], "#,0")  & " "& FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([Response_Count_LYQTR_2024_ON], "#,0")  & " "& FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"),
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([Response_Count_LYQTR_2024_ON], "#,0")  & " "& FORMAT([Recommand_LYQTR%_2024_ON], "0.0%"))))))
			```
		lineageTag: f382b853-aef8-4947-94dc-d92747080e9e

	measure 'QTR to QTR1_NEW_VERSION' = ```
			
			 
			IF(
			    SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "RESPONDED",
			    CALCULATE(
			        [CYQTR-LYQTR_variance_2024_ON] * 100,
			        ALLSELECTED()
			    ),
			    IF(
			        SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "SURVEYED",
			        BLANK(),
			        IF(
			            SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Yes",
			            IF([QTR to QTR] >= 0, "+" & FORMAT([QTR to QTR] * 100, "0"), FORMAT([QTR to QTR] * 100, "0")),
			            IF(
			                SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "No",
			                IF([QTR to QTR] >= 0, "+" & FORMAT([QTR to QTR] * 100, "0"), FORMAT([QTR to QTR] * 100, "0")),
			                IF(
			                    SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Unknown",
			                    IF([QTR to QTR] >= 0, "+" & FORMAT([QTR to QTR] * 100, "0"), FORMAT([QTR to QTR] * 100, "0"))
			                )
			            )
			        )
			    )
			)
			
			
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			//  CALCULATE( FORMAT([CYQTR-LYQTR_variance_2024_ON], "0.00%"),ALLSELECTED()),
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",BLANK(),
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([QTR to QTR], "0.00%"),
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([QTR to QTR], "0.00%"),
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([QTR to QTR], "0.00%"))))))
			```
		lineageTag: a49f1830-ea60-4e45-9351-9ef3314534d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD to YTD1_New_Version' =
			
			
			IF(
			    SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "RESPONDED",
			    CALCULATE(
			        [CYTD-LYTD_variance_2024_ON] * 100,
			        ALLSELECTED()
			    ),
			    IF(
			        SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "SURVEYED",
			        BLANK(),
			        IF(
			            SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Yes",
			            IF([YTD to YTD] >= 0, "+" & FORMAT([YTD to YTD] * 100, "0"), FORMAT([YTD to YTD] * 100, "0")),
			            IF(
			                SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "No",
			                IF([YTD to YTD] >= 0, "+" & FORMAT([YTD to YTD] * 100, "0"), FORMAT([YTD to YTD] * 100, "0")),
			                IF(
			                    SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Unknown",
			                    IF([YTD to YTD] >= 0, "+" & FORMAT([YTD to YTD] * 100, "0"), FORMAT([YTD to YTD] * 100, "0"))
			                )
			            )
			        )
			    )
			)
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="RESPONDED",
			//  CALCULATE( FORMAT([CYTD-LYTD_variance_2024_ON], "0.0%"),ALLSELECTED()),
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="SURVEYED",BLANK(),
			
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Yes",FORMAT([YTD to YTD], "0.0%"),
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="No",FORMAT([YTD to YTD], "0.0%"),
			//  if(SELECTEDVALUE('Dim Recommend Galen'[Recommend])="Unknown",FORMAT([YTD to YTD], "0.0%"))))))
		lineageTag: e5a0c47a-fcc0-422e-85e9-0955b9782da3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LY_YTD_2024_ON = ```
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "RESPONDED",
			CALCULATE(COALESCE(FORMAT([Response_Count_LYTD], "#,0") & " (" & FORMAT([Response_LYTD%], "0.0%") & ")", 
			FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " (" & FORMAT([Response_LYTD%_2024_ON], "0.0%") & ")"),
			ALLSELECTED()),
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "SURVEYED",
			CALCULATE(COALESCE(FORMAT([Surveyed_LYTD_FInal], "#,0"), 
			FORMAT([Surveyed_LYTD_FInal_2024_ON], "#,0")),ALLSELECTED()),
			         
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Yes",
			COALESCE(
			FORMAT([Response_Count_LYTD], "#,0") & " " & FORMAT([Recommand_LYTD%], "0.0%"),
			FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " " & FORMAT([Recommand_LYTD%_2024_ON], "0.0%")),
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "No",
			COALESCE(
			    FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " " & FORMAT([Recommand_LYTD%_2024_ON], "0.0%"),
			FORMAT([Response_Count_LYTD], "#,0") & " " & FORMAT([Recommand_LYTD%], "0.0%")),
			//FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " " & FORMAT([Recommand_LYTD%_2024_ON], "0.0%")),
			
			IF(SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Unknown",
			COALESCE(FORMAT([Response_Count_LYTD], "#,0") & " " & FORMAT([Recommand_LYTD%], "0.0%"),
			FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " " & FORMAT([Recommand_LYTD%_2024_ON], "0.0%")))))))
			
			// IF(
			//     SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "RESPONDED",
			//     CALCULATE(
			//         COALESCE(
			//             FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " (" & FORMAT([Response_LYTD%_2024_ON], "0.0%") & ")",
			//             ""
			//         ),
			//         ALLSELECTED()
			//     ),
			//     IF(
			//         SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "SURVEYED",
			//         CALCULATE(
			//             COALESCE(
			//                 FORMAT([surveyed_LYTD_Final_2024_on], "#,0"),
			//                 ""
			//             ),
			//             ALLSELECTED()
			//         ),
			//         IF(
			//             SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Yes",
			//             COALESCE(
			//                 FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " " & FORMAT([Recommand_LYTD%_2024_ON], "0.0%"),
			//                 ""
			//             ),
			//             IF(
			//                 SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "No",
			//                 COALESCE(
			//                     FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " " & FORMAT([Recommand_LYTD%_2024_ON], "0.0%"),
			//                     ""
			//                 ),
			//                 IF(
			//                     SELECTEDVALUE('Dim Recommend Galen'[Recommend]) = "Unknown",
			//                     COALESCE(
			//                         FORMAT([Response_Count_LYTD_2024_ON], "#,0") & " " & FORMAT([Recommand_LYTD%_2024_ON], "0.0%"),
			//                         ""
			//                     )
			//                 )
			//             )
			//         )
			//     )
			// )
			
			```
		lineageTag: c12604e9-8951-49b0-8ff4-2c146786e81c

	column Recommend
		dataType: string
		lineageTag: 4173382c-3ee9-4cd6-a896-fe20616e8595
		summarizeBy: none
		sourceColumn: Recommend
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: c34cf0db-69f9-4dce-9294-a4f4326ef7df
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition 'Dim Recommend Galen' = m
		mode: import
		queryGroup: Surveys
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WinQNVtJRMlSK1YlW8vMHMo3AzFA/bz//cD8g3xjMD3INDvD3c3F1AYqYgEWCQ4PCXCPBAqZKsbEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Recommend = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Recommend", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

