table DIM_Gender
	lineageTag: 80336555-b7c2-40af-8438-c90675f00dae

	measure Female = DIVIDE(CALCULATE([Student Count],DIM_Gender[Gender] = "F"),[Student Count],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9ff432ec-d19b-4037-ac81-2ad839ae4d09

	measure Male = DIVIDE(CALCULATE([Student Count],DIM_Gender[Gender] = "M"),[Student Count],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: be279a9b-7b82-471b-8757-7a3e3548b1bf

	column Gender
		dataType: string
		lineageTag: 8aba4be1-53ec-40b6-b337-277fb74bad2d
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	partition DIM_Gender = m
		mode: import
		queryGroup: Students
		source =
				let
				    Source = #"Diversity - Remove",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Gender"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates",null,"N/A",Replacer.ReplaceValue,{"Gender"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

