table DIM_TBA_Headers
	lineageTag: d0e874e8-bc17-4692-8ec7-c9aa24231002

	column Type
		dataType: string
		lineageTag: d96c9fb7-87f1-4471-a4c3-a9f90434d71e
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Header
		dataType: string
		lineageTag: 88f93b5c-6629-43f3-b6fb-a4e2c8d52e6d
		summarizeBy: none
		sourceColumn: Header

		annotation SummarizationSetBy = Automatic

	partition DIM_TBA_Headers = m
		mode: import
		queryGroup: Academics
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs7JzMtMTsxR0lFyLi0qSs0rUYrViVbySUxCF0lNLiktSkUThbF1lNyLEvNSFELyS4BmgWTcSqHK0SWQbISqQViILAC3DyYYCwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Type = _t, Header = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Type", type text}, {"Header", type text}})
				in
				    #"Changed Type"

