table DIM_Terms
	lineageTag: f1dbc49a-8159-4286-ac47-6fabf9437998

	measure CurrentYearCompletedQuarter = ```
			
			VAR CurrentDate = TODAY()
			VAR YearStart = DATE(YEAR(CurrentDate), 1, 1)
			VAR CurrentQuarter = 
			    QUOTIENT(MONTH(CurrentDate) - 1, 3) + 1
			VAR CompletedQuarter =
			    SWITCH(
			        TRUE(),
			        CurrentQuarter = 1,"4th QTR " & FORMAT(YEAR(YearStart)-1, "0000"),  // Q1 has no completed quarter
			        CurrentQuarter = 2, "1st QTR " & FORMAT(YEAR(YearStart), "0000"),  // Q2 completed Q1
			        CurrentQuarter = 3, "2nd QTR " & FORMAT(YEAR(YearStart), "0000"),  // Q3 completed Q2
			        CurrentQuarter = 4, "3rd QTR " & FORMAT(YEAR(YearStart), "0000"),  // Q4 completed Q3
			        BLANK()  // Default case, should not be reached
			    )
			
			RETURN
			    CompletedQuarter
			
			```
		lineageTag: 48a8898b-44b0-4df6-816a-ec7cea748541

		changedProperty = IsHidden

	measure PreviousYearSameQuarter = ```
			
			
			VAR CurrentDate = TODAY()
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarter = QUOTIENT(CurrentMonth - 1, 3) + 1
			VAR CompletedQuarter = CurrentQuarter - 1
			VAR YearToUse = IF(CompletedQuarter = 0, YEAR(CurrentDate) - 2, YEAR(CurrentDate) - 1)
			VAR QuarterLabel = 
			    SWITCH(
			        TRUE(),
			        CompletedQuarter = 1, "1st QTR ",
			        CompletedQuarter = 2, "2nd QTR ",
			        CompletedQuarter = 3, "3rd QTR ",
			        CompletedQuarter = 4, "4th QTR ",
			        "No completed quarter"
			    )
			RETURN
			    IF(CompletedQuarter = 0, "4th QTR " & FORMAT(YearToUse, "0000"), QuarterLabel & FORMAT(YearToUse, "0000"))
			
			// VAR CurrentDate = TODAY()
			// VAR YearStart = DATE(YEAR(CurrentDate), 1, 1)
			// VAR CurrentQuarter = 
			//     QUOTIENT(MONTH(CurrentDate) - 1, 3) + 1
			// VAR CompletedQuarter =
			//     SWITCH(
			//         TRUE(),
			//         CurrentQuarter = 1, "4th QTR " & FORMAT(YEAR(YearStart) - 2, "0000"),  
			//         CurrentQuarter = 2, "1st QTR " & FORMAT(YEAR(YearStart), "0000"),      
			//         CurrentQuarter = 3, "2nd QTR " & FORMAT(YEAR(YearStart), "0000"),    
			//         CurrentQuarter = 4, "3rd QTR " & FORMAT(YEAR(YearStart), "0000"),     
			//         BLANK()                                                               
			//     )
			
			// RETURN
			//     CompletedQuarter
			
			
			```
		lineageTag: f3223136-d48e-41c4-bf88-9e4ccc755624

		changedProperty = IsHidden

	measure 'YTD CurrentYear_Name' =
			
			var CurrentYear = YEAR(TODAY())
			Return
			"YTD_"&CurrentYear
		lineageTag: 95d4a5da-fcdc-4665-b7c4-bec220b9e4dc

		changedProperty = IsHidden

	measure 'YTD Previous_Name' =
			
			var CurrentYear = (YEAR(TODAY()))-1
			RETURN
			"YTD_"&CurrentYear
		lineageTag: c5980ab0-d075-45cc-a00d-6d82804b99cc

		changedProperty = IsHidden

	measure CurrentQTR = "Quarter " & QUARTER(TODAY())
		lineageTag: e233da03-1254-45fc-8cad-b54e7f33ebed

		changedProperty = IsHidden

	measure NextGround = ```
			
			CALCULATE(
			    MIN(Dim_TERMS[TERM_START_DATE]),
			    FILTER(
			        DIM_Terms, 
			        RIGHT(Dim_Terms[TERMS_ID], 1) = "Q" && Dim_Terms[TERM_START_DATE] > TODAY()
			    )
			)
			```
		formatString: General Date
		lineageTag: c1d379dc-1300-401d-bb1a-833ab3dc1384

		changedProperty = IsHidden

	measure NextOnline = ```
			
			CALCULATE(
			    MIN(DIM_Terms[TERM_START_DATE]),
			    FILTER(
			        DIM_Terms, 
			        (RIGHT(DIM_Terms[TERMS_ID], 1) = "1" || RIGHT(DIM_Terms[TERMS_ID], 1) = "2") && DIM_Terms[TERM_START_DATE] > TODAY()
			    )
			)
			```
		formatString: General Date
		lineageTag: 76a53efc-46dc-4510-a57b-5154a73496d8

		changedProperty = IsHidden

	measure YTDToYTD = "YTD TO YTD"
		lineageTag: a8ee6e19-7d00-4b8e-94a0-8bdaf9179d89

		changedProperty = IsHidden

	measure QTRtoQTR = "QTR to QTR"
		lineageTag: c5cc7b6a-d260-4f1f-bda9-f5d6efc6bc8f

		changedProperty = IsHidden

	measure Future_Term_Display = ```
			
			"Future (" & 
			CALCULATE(
			    SELECTEDVALUE('DIM_Terms'[TERMS_ID]), 
			    'DIM_Terms'[NextTerm] = "Ground"
			) & ")"
			
			```
		lineageTag: df506252-6ab8-41bd-9adb-70c13c6953c3

	measure Current_Ground_Term = ```
			
			"Current (" & 
			CALCULATE(
			    SELECTEDVALUE('DIM_Terms'[Terms_ID]),
			    'DIM_Terms'[CurrentTerm] = "TRUE",
			    'DIM_Terms'[Modality] = "Ground"
			) & ")"
			
			```
		lineageTag: 2962233b-ca1a-4138-b2ef-170851a6368a

	column TERMS_ID
		dataType: string
		lineageTag: 20a65957-0f03-423a-9560-adeb8776e492
		summarizeBy: none
		sourceColumn: TERMS_ID
		sortByColumn: TERM_START_DATE

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TERM_START_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: ed65ad06-a108-4186-b4b0-07512b10ff0b
		summarizeBy: none
		sourceColumn: TERM_START_DATE

		variation Variation
			isDefault
			relationship: cfb07c8c-3a71-4391-98d5-41545fef1c48
			defaultHierarchy: LocalDateTable_a9e13912-918c-4745-be46-601b932db6e8.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TERM_END_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: b9584f98-b026-4235-9f4a-f19f78949986
		summarizeBy: none
		sourceColumn: TERM_END_DATE

		variation Variation
			isDefault
			relationship: 16bf795d-f7f6-426c-b48a-9815d9f9f69b
			defaultHierarchy: LocalDateTable_311a1878-faa7-424a-af37-7eae50172fd3.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modality = SWITCH(RIGHT(DIM_Terms[TERMS_ID],1),"Q","Ground","1","Online","2","Online","N/A")
		lineageTag: 70cd3d39-42a0-493e-b7a2-d907919444f3
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsNextTerm = IF(DIM_Terms[NextTerm]="Ground" || DIM_Terms[NextTerm] = "Online", True(), False())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9d00d5e5-0edf-4e11-90fd-ad22b3c3fc7d
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsCurrentTerm = SWITCH(TRUE(),TODAY() >=DIM_Terms[TERM_START_DATE] && TODAY()  <=DIM_Terms[TERM_END_DATE],TRUE(),False())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: eb538b83-ef8e-44ec-8392-a3a6f1a5d99e
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter = ```
			SWITCH(RIGHT([TERMS_ID],3),"FAQ","Q3 " & LEFT([TERMS_ID],4), 
			"SPQ","Q1 " & LEFT([TERMS_ID],4),"SUQ","Q2 " & LEFT([TERMS_ID],4),"WIQ","Q4 " & LEFT([TERMS_ID],4))
			```
		lineageTag: 5995eabb-2e9b-4f8c-9db0-de7d20602bd6
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentYearCompletedQuarterFlag = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentQuarterStart = 
			    DATE(
			        YEAR(CurrentDate), 
			        1 + 3 * QUOTIENT(MONTH(CurrentDate) - 1, 3), ---4/1/2025
			        1
			    )
			VAR CurrentQuarterEnd = 
			    EOMONTH(
			        DATE(
			            YEAR(CurrentDate), 
			            1 + 3 * QUOTIENT(MONTH(CurrentDate) - 1, 3) + 2, --- 6/30/2025
			            1
			        ), 
			        0
			    )
			VAR CompletedQuarterStart = 
			    EDATE(CurrentQuarterStart, -3)   ---1/1/2025
			VAR CompletedQuarterEnd = 
			    EOMONTH(EDATE(CurrentQuarterEnd, -2), 0)  ---3/31/2025
			VAR StartDate = EOMONTH(EDATE(DIM_Terms[TERM_START_DATE],-1),0)+1 ---1/1/2025
			VAR EndDate = DIM_Terms[TERM_END_DATE] --- 3/25/2025 & 4/22/2025
			
			RETURN
			
			 IF(
			    StartDate >= CompletedQuarterStart &&  ---Jan/6/2025<Jan/1/2025----
			    EndDate <= CompletedQuarterEnd &&   ----3/25/2025 & 4/22/2025---3/31/2025
			    StartDate <= EndDate,
			     1, 
			     0   
			)
			
			```
		formatString: 0
		lineageTag: 4f954a06-3b8d-43be-8bfc-8af7d5b3123c
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DatesInCompletedQuarterPreviousYear = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentQuarter = 
			    1 + 3 * QUOTIENT(MONTH(CurrentDate) - 1, 3)
			VAR CompletedQuarterEnd = 
			    EOMONTH(
			        DATE(
			            CurrentYear,
			            CurrentQuarter - 1,
			            1
			        ), 
			        0
			    )
			VAR PreviousYear1 = CurrentYear - 1
			VAR CompletedQuarterStart = 
			    DATE(
			        PreviousYear1,
			        1 + 3 * QUOTIENT(MONTH(CompletedQuarterEnd) - 1, 3),
			        1
			    )
			VAR PreviousQuarterEnd = 
			    EOMONTH(
			        DATE(
			            PreviousYear1,
			            1 + 3 * QUOTIENT(MONTH(CompletedQuarterEnd) - 1, 3) + 2,
			            1
			        ), 
			        0
			    )
			VAR StartDate = DIM_Terms[TERM_START_DATE]
			VAR EndDate = DIM_Terms[TERM_END_DATE]
			
			return
			IF(
			    StartDate >= CompletedQuarterStart &&
			    EndDate <= PreviousQuarterEnd &&
			    EndDate >= CompletedQuarterStart &&
			    StartDate <= PreviousQuarterEnd,
			    1,  
			    0 
			)
			
			
			```
		formatString: 0
		lineageTag: 23d21b26-2956-4dba-8287-bbe39c6235a1
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YTDFlag = ```
			
			VAR CurrentDate = TODAY()
			VAR YearStartDate = DATE(YEAR(CurrentDate), 1, 1)
			VAR StartDate = DIM_Terms[TERM_START_DATE]
			VAR EndDate = DIM_Terms[TERM_END_DATE]
			
			RETURN
			IF(
			    StartDate >= YearStartDate &&
			    EndDate <= CurrentDate &&
			    StartDate <= EndDate,
			    1,  // Return 1 (True) if the date range is within the YTD period
			    0   // Return 0 (False) otherwise
			)
			
			```
		formatString: 0
		lineageTag: 5bf88744-45fb-4daf-a90b-3a92cbed20f4
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastYearYTDFlag = ```
			
			VAR termyearText = LEFT(DIM_Terms[TERMS_ID], 4) 
			VAR termyear = 
			    IF(
			        ISERROR(VALUE(termyearText)), 
			        BLANK(), 
			        VALUE(termyearText) 
			    )
			VAR lastyear = YEAR(TODAY()) - 1
			RETURN
			IF(
			    NOT(ISBLANK(termyear)) && termyear = lastyear, 
			    1, 
			    0
			)
			
			
			
			
			```
		formatString: 0
		lineageTag: 515fc7e4-3af1-49e6-9e2e-fb78d46a71e0
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NextTermIndicator =
			IF(DIM_Terms[TERM_START_DATE] == [NextGround] , 1 ,
			 IF(DIM_Terms[TERM_START_DATE]==[NextOnline],1,0))
		formatString: 0
		lineageTag: 9a9920a4-655c-4c5e-b0a5-d15145f0c3f4
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FACULTYATTRITIONTERMS
		dataType: int64
		formatString: 0
		lineageTag: ff3f8fbd-cae5-4ba9-b3fe-cdab129eca46
		summarizeBy: sum
		sourceColumn: FACULTYATTRITIONTERMS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NextTerm
		dataType: string
		lineageTag: 22a165b1-d4c5-4a69-a9b3-466d38986a5b
		summarizeBy: none
		sourceColumn: NextTerm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Term_Sort
		dataType: int64
		formatString: 0
		lineageTag: bf98b737-7a35-4976-a170-ee4f08472b4d
		summarizeBy: sum
		sourceColumn: Term_Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentTerm
		dataType: string
		lineageTag: d38c8aad-518a-4b03-99ac-d21cb4e9319e
		summarizeBy: none
		sourceColumn: CurrentTerm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FacultyLoadTerms
		dataType: int64
		formatString: 0
		lineageTag: 38739ee5-4f21-408c-8d53-bacd4740f81f
		summarizeBy: sum
		sourceColumn: FacultyLoadTerms

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QuarterFaculty = IF(ISBLANK(DIM_Terms[FacultyLoadTerms])=FALSE(),[Quarter],blank())
		lineageTag: ea711a92-fd87-4468-ab9c-3ab6c99df34d
		summarizeBy: none
		sortByColumn: FacultyLoadTerms

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentTermWithBreak
		dataType: string
		lineageTag: ab92eab6-fc0e-441e-974f-b60fe7986db5
		summarizeBy: none
		sourceColumn: CurrentTermWithBreak

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NEXT_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: d54a4b42-f74a-42c2-a3dd-3aea9769d626
		summarizeBy: none
		sourceColumn: NEXT_START_DATE

		variation Variation
			isDefault
			relationship: ac24c029-a0ca-4c85-9459-4b6175f84a75
			defaultHierarchy: LocalDateTable_d63b13eb-3572-49fe-aac9-e75185736a5f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TermDuringBreak = ```
			
			
			
			
			IF(
			    TODAY() >= DIM_Terms[TERM_START_DATE] 
			    && (TODAY() <= DIM_Terms[NEXT_START_DATE]-1 || TODAY() <= DIM_Terms[TERM_END_DATE]),
			    "True",
			    "False"
			)
			
			```
		lineageTag: 53fedf7a-5095-42d8-8c44-3f34ab82784d
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TermDuringBreak_LastYear = ```
			
			
			
			IF(
			    DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) >= DIM_Terms[TERM_START_DATE] 
			    && (DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) < (DIM_Terms[NEXT_START_DATE] - 1) || 
			        DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) <= DIM_Terms[TERM_END_DATE]),
			    "True",
			    "False"
			)
			
			
			// IF(
			//     DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) >= DIM_Terms[TERM_START_DATE] 
			//     && (DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) <= DIM_Terms[NEXT_START_DATE] || 
			//         DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) <= DIM_Terms[TERM_END_DATE]),
			//     "True",
			//     "False"
			// )
			
			```
		lineageTag: 430b1baf-c56f-4be9-8cba-d6b6d169c994
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Next_Start_Date1 = ```
			
			//DATEVALUE(DIM_Terms[NEXT_START_DATE])
			IF(
			    ISBLANK(Dim_Terms[NEXT_START_DATE]),
			    BLANK(),
			    DATEVALUE(DIM_Terms[NEXT_START_DATE]))
			
			```
		formatString: dd/mm/yyyy
		lineageTag: acc0abaa-cb7d-44a8-a7f6-a6e28c94d80d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 80a35202-b7f4-4b58-ac13-5e07adc6303b
			defaultHierarchy: LocalDateTable_5cf5300d-f462-4f39-9502-64eea02e415b.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Is_Last_Year_Today_Between = ```
			
			IF(
			    DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) >= 'Dim_Terms'[TERM_START_DATE] &&
			    DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) <= 'DIM_Terms'[NEXT_START_DATE],
			    "TRUE",
			    "FALSE"
			)
			
			```
		lineageTag: cbf5f4bb-a000-45eb-9972-43f0d50f0e13
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column last_year_current_quarter = ```
			
			IF(
			    DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) >= 'Dim_Terms'[TERM_START_DATE] &&
			    DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY())) <= 'DIM_Terms'[TERM_END_DATE],
			    "TRUE",
			    "FALSE"
			)
			
			```
		lineageTag: 2b0dac6a-577c-403f-9780-2e8f72b26fba
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Next_start_date_oneday = IF(DIM_Terms[NEXT_START_DATE]=BLANK(),BLANK(),DIM_Terms[NEXT_START_DATE]-1)
		formatString: General Date
		lineageTag: e19f479e-e8ae-4d78-aad0-a8427e914172
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 72ad87e1-64c7-470e-8529-cc08c72c3b14
			defaultHierarchy: LocalDateTable_70dd7367-1278-4238-8494-f40597896fe4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PreviousYearCompletedQuarter = ```
			
			VAR CurrentDate = DATE ( YEAR ( NOW () ) - 1, MONTH ( NOW () ), DAY ( NOW () ) )
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentQuarter = 
			    1 + 3 * QUOTIENT(MONTH(CurrentDate) - 1, 3)
			VAR CompletedQuarterEnd = 
			    EOMONTH(
			        DATE(
			            CurrentYear,
			            CurrentQuarter - 1,
			            1
			        ), 
			        0
			    )
			VAR PreviousYear1 = CurrentYear - 0
			VAR CompletedQuarterStart = 
			    DATE(
			        PreviousYear1,
			        1 + 3 * QUOTIENT(MONTH(CompletedQuarterEnd) - 1, 3),
			        1
			    )
			VAR PreviousQuarterEnd = 
			    EOMONTH(
			        DATE(
			            PreviousYear1,
			            1 + 3 * QUOTIENT(MONTH(CompletedQuarterEnd) - 1, 3) + 3, --- 3/31/2024, 3/31/2024
			            1
			        ), 
			        0
			    )
			VAR StartDate = DIM_Terms[TERM_START_DATE] --- 1/8/2024, 1/8/2024
			VAR EndDate = DIM_Terms[TERM_END_DATE] -- 3/26/2024 , 4/23/2024
			
			return
			
			IF(
			   StartDate >= CompletedQuarterStart   --1,1
			      && EndDate <= PreviousQuarterEnd   -- 0,0   -- 3/26/2024 , 4/23/2024
			    && EndDate >= CompletedQuarterStart     -- 1,1
			       && StartDate <= PreviousQuarterEnd --0,0
			    ,1,  
			    0 
			)
			
			
			```
		formatString: 0
		lineageTag: 9d81346f-5845-40db-8264-e27e141f5b66
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column YTDFlag_demographics = ```
			
			VAR CurrentYear = YEAR(TODAY())
			
			RETURN
			IF(
			    YEAR(DIM_Terms[TERM_START_DATE]) = CurrentYear
			        && DIM_Terms[TERM_END_DATE] < TODAY(),
			    1,
			    0
			)
			
			// IF(
			//     YEAR(DIM_Terms[TERM_START_DATE]) = YEAR(TODAY()),
			//     1,
			//     0
			// )
			
			
			
			// VAR MinYear = YEAR(
			//     CALCULATE(
			//         MIN(DIM_Terms[TERM_START_DATE]),
			//         ALL(),
			//         DIM_Terms[IsCurrentTerm] = TRUE()
			//     )
			// )
			
			// VAR CurrentTermYear = YEAR(
			//     CALCULATE(
			//         MIN(DIM_Terms[TERM_START_DATE])
			//     )
			// )
			
			// RETURN
			// IF(
			//     MinYear = YEAR(TODAY()) - 1 && MinYear = CurrentTermYear,
			//     1,
			//     IF(MinYear = YEAR(TODAY()), 1, 0)
			// )
			
			
			// VAR MinYear =  YEAR(CALCULATE(MIN(DIM_Terms[TERM_START_DATE]),ALL(),DIM_Terms[IsCurrentTerm]=TRUE()))
			
			// RETURN
			// IF(MinYear=YEAR(TODAY())-1 && MinYear=YEAR(DIM_Terms[TERM_START_DATE]),1,
			// IF(MinYear=YEAR(TODAY()),1,0))
			
			```
		formatString: 0
		lineageTag: 4bfa4377-69fd-4e06-a948-933c717ecef8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column LastYearYTDFlag_Satisfaction =
			
			VAR MinYear =
			    YEAR(
			        CALCULATE(
			            MIN(DIM_Terms[TERM_START_DATE]),
			            ALL(),DIM_Terms[TermDuringBreak_LastYear]="True"
			        )
			    )
			RETURN
			    IF(
			        MinYear = YEAR(TODAY()) - 2 && MinYear = YEAR(DIM_Terms[TERM_START_DATE]),
			        1,
			        IF(MinYear = YEAR(TODAY()) - 1, 1, 0)
			    )
		formatString: 0
		lineageTag: de271b3a-74d3-4ded-9d72-89196c8e76e8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DIM_Terms = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "coll18_repl_production", [Query="WITH FacAttritionTerms AS (#(lf)SELECT TOP 8 TERMS_ID, TERM_START_DATE, TERM_END_DATE , DENSE_RANK() OVER (ORDER BY TERM_START_DATE DESC) AS TERMS_RANKED#(lf)FROM TERMS#(lf)WHERE 1 = 1#(lf)AND DATEADD(WEEK,2,TERM_START_DATE) <= GETDATE()#(lf)AND RIGHT(TERMS_ID,1) = 'Q'#(lf)),#(lf)NextGroundTerm AS (#(lf)SELECT TOP 1 TERMS_ID, TERM_START_DATE, TERM_END_DATE , DENSE_RANK() OVER (ORDER BY TERM_START_DATE DESC) AS TERMS_RANKED#(lf)FROM TERMS#(lf)WHERE 1 = 1#(lf)AND TERM_START_DATE > GETDATE()#(lf)AND RIGHT(TERMS_ID,1) = 'Q'#(lf)ORDER BY TERM_START_DATE ASC),#(lf)CurrentTermWithBreak AS (#(lf)SELECT LEAD(TERM_START_DATE) OVER (ORDER BY TERM_START_DATE ASC) NEXT_START_DATE, TERM_START_DATE CURRENT_START_DATE, TERMS_ID#(lf)FROM TERMS#(lf)WHERE 1 = 1#(lf)--AND TERM_START_DATE < GETDATE()#(lf)AND RIGHT(TERMS_ID,1) = 'Q'#(lf)),#(lf)NextOnlineTerm AS (#(lf)SELECT TOP 1 TERMS_ID, TERM_START_DATE, TERM_END_DATE , DENSE_RANK() OVER (ORDER BY TERM_START_DATE DESC) AS TERMS_RANKED#(lf)FROM TERMS#(lf)WHERE 1 = 1#(lf)AND TERM_START_DATE > GETDATE()#(lf)AND RIGHT(TERMS_ID,1) IN ('1','2')#(lf)ORDER BY TERM_START_DATE ASC),#(lf)FacultyLoadTerms as (#(lf)SELECT TOP 5 TERM_START_DATE, TERMS_ID, ROW_NUMBER () OVER (ORDER BY TERM_START_DATE DESC) AS SO#(lf)FROM TERMS CT#(lf)WHERE RIGHT(CT.TERMS_ID, 1) = 'Q'#(lf)AND GETDATE() >= TERM_START_DATE#(lf)ORDER BY TERM_START_DATE DESC)#(lf)#(lf)SELECT T.TERMS_ID,T.TERM_START_DATE,T.TERM_END_DATE, Ft.TERMS_RANKED AS FACULTYATTRITIONTERMS, CASE WHEN Gt.TERMS_RANKED IS NOT NULL THEN 'Ground' WHEN Ot.TERMS_RANKED IS NOT NULL THEN 'Online' ELSE NULL END AS#(lf)NextTerm, DENSE_RANK() OVER (ORDER BY T.TERM_START_DATE DESC) AS Term_Sort#(lf), CASE WHEN GETDATE() BETWEEN T.TERM_START_DATE AND T.TERM_END_DATE THEN 'True' ELSE NULL END CurrentTerm#(lf), CASE WHEN GETDATE() BETWEEN T.TERM_START_DATE AND Gt.TERM_START_DATE  THEN 'True' ELSE NULL END CurrentTermWithBreak#(lf),Ct.NEXT_START_DATE#(lf), CASE WHEN Lt.TERMS_ID IS NOT NULL THEN Lt.SO ELSE NULL END AS FacultyLoadTerms#(lf)FROM TERMS T#(lf)LEFT JOIN FacAttritionTerms Ft ON Ft.TERMS_ID = T.TERMS_ID#(lf)LEFT JOIN NextGroundTerm Gt ON Gt.TERMS_ID = T.TERMS_ID#(lf)LEFT JOIN NextOnlineTerm Ot ON Ot.TERMS_ID = T.TERMS_ID#(lf)LEFT JOIN FacultyLoadTerms Lt ON Lt.TERMS_ID = T.TERMS_ID#(lf)LEFT JOIN CurrentTermWithBreak Ct ON T.TERMS_ID = Ct.TERMS_ID#(lf)"])
				in
				    Source

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

