table 'Enrollment Budget'
	lineageTag: 16713cfc-dca5-4f7f-b71f-b1bc1aab1cf3

	measure Current_Month_Budget =
			
			var currentyear = YEAR(TODAY())
			var currentMonth= MONTH(TODAY())
			VAR FINAL =
			CALCULATE(SUM('Enrollment Budget'[Value]),
			YEAR('Enrollment Budget'[Date])= currentyear,
			MONTH('Enrollment Budget'[Date])= currentMonth)
			RETURN
			IF(FINAL = BLANK(),0,FINAL)+0
		formatString: #,0
		lineageTag: 344ac0be-95fd-4b14-a4d3-d93e244f9e33

	measure Budget_Percentage = ```
			
			
			VAR Overall = DISTINCTCOUNT('Active Students DSET'[STUDENT_ID])
			VAR Budget = [Current_Month_Budget]
			VAR Ratio = DIVIDE(Overall, Budget, 0)  -- Calculate Overall / Budget
			VAR Difference = Ratio - 1  -- Subtract 1 from the Ratio to get the difference
			VAR Percentage = Difference * 100  -- Convert the difference to percentage
			
			RETURN 
			    IF(
			        Overall > Budget,  -- If Overall is greater than Budget, return positive percentage
			        CONCATENATE("+", FORMAT(Percentage, "0.00") & "%"),  -- Format it as a positive percentage
			        CONCATENATE("-", FORMAT(ABS(Percentage), "0.00") & "%")  -- Format it as a negative percentage
			    )
			
			
			
			
			// VAR A = DISTINCTCOUNT ('Active Students DSET'[STUDENT_ID]) / [Current_Month_Budget] 
			// RETURN
			//     IF(
			//         DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]) > [Current_Month_Budget],             
			//         CONCATENATE("+", FORMAT(DIVIDE(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]),[Current_Month_Budget],0), "0.00%")),      
			//         CONCATENATE("-", FORMAT(ABS(DIVIDE(DISTINCTCOUNT('Active Students DSET'[STUDENT_ID]),[Current_Month_Budget],0)), "0.00%"))   
			//     )
			```
		lineageTag: 5e27cc80-802f-41de-be7c-af7b79287528

	measure BudgetFlag = IF(COUNT('Active Students DSET'[STUDENT_ID])>[Current_Month_Budget], UNICHAR(9650), UNICHAR(9660))
		lineageTag: 3555fc4a-f3c9-4e68-8513-8251b8f13ed8

	measure EnrollmentBudgetFlag = IF(COUNT('Active Students DSET'[STUDENT_ID])>[Current_Month_Budget], "#00B050", "#C81515")
		lineageTag: bba7b1d5-ecb0-462a-a0cf-8517e9b41797

	column Campus
		dataType: string
		lineageTag: 0708d10d-6bb3-4d47-a10a-1c9347d63756
		summarizeBy: none
		sourceColumn: Campus

		annotation SummarizationSetBy = Automatic

	column Program
		dataType: string
		lineageTag: 8293861e-563b-4f80-b12a-1142b9a56bd3
		summarizeBy: none
		sourceColumn: Program

		annotation SummarizationSetBy = Automatic

	column 'HCA Indicator'
		dataType: string
		lineageTag: 74e41b2d-f39c-4548-a8a8-e887015eeca3
		summarizeBy: none
		sourceColumn: HCA Indicator

		annotation SummarizationSetBy = Automatic

	column Returning
		dataType: int64
		formatString: 0
		lineageTag: b032ac72-ef5e-490e-b812-ef5fff6f610f
		summarizeBy: sum
		sourceColumn: Returning

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 752d5715-92d8-434d-ac75-8b9bc11254bd
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: eb5f5356-cb30-4c9d-8b91-5078b9720e7b
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 7843a792-4b0f-4986-8dd1-a14c3b0dae9e
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Date = DATE('Enrollment Budget'[Year],'Enrollment Budget'[Month_No],1)
		formatString: General Date
		lineageTag: 8a41c4da-4552-44c7-815e-47454d07f70b
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 2f55ca65-9938-4060-b066-90d7e9baaed5
			defaultHierarchy: LocalDateTable_bda6dc7b-012d-4de0-982a-a116240cd622.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Month_No = SWITCH('Enrollment Budget'[Month], "January",1, "February",2, "March",3, "April",4, "May",5, "June",6, "July",7, "August",8, "September", 9, "October",10, "November",11, "December",12)
		formatString: 0
		lineageTag: b9ae928e-acd3-4514-bee7-b689bc0328a9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Campus_New = LOOKUPVALUE('Campus Region'[LOCATIONS_ID],'Campus Region'[LOCATIONS_ID],[Campus],"OTHER")
		lineageTag: ed699288-a710-46e2-8d1b-3bd455f21c67
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Enrollment Budget' = m
		mode: import
		queryGroup: Students
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://hcahealthcare.sharepoint.com/sites/HTPS-GalenCollaboration/Shared%20Documents/Project%20Folder/Executive%20Dashboards/Student%20Enrollment%20Budget.xlsx"), null, true),
				    Enrollment_Sheet = Source{[Item="Enrollment",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Enrollment_Sheet, [PromoteAllScalars=true]),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"Campus", "Program", "HCA Indicator", "Returning", "Year"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Month"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Campus", type text}, {"Program", type text}, {"HCA Indicator", type text}, {"Returning", Int64.Type}, {"Year", Int64.Type}, {"Month", type text}, {"Value", Int64.Type}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type1", {{"Returning", null}}),
				    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Replaced Errors", {{"Value", null}})
				in
				    #"Replaced Errors1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

