table 'FACT_Theory Enrollment'
	lineageTag: e6165234-2c72-4709-9e5f-b7fee72e8591

	measure <15 = SUM('FACT_Theory Enrollment'[LESS_THAN_15])+0
		formatString: 0
		lineageTag: 48e763f3-3c22-4417-bec0-9e9f975566ea

	measure >45 = SUM('FACT_Theory Enrollment'[MORE_THAN_45])+0
		formatString: 0
		lineageTag: 30233384-42ce-4379-948a-fd54f3b3d686

	measure <15_Color =
			
			VAR ThoeryCY = CALCULATE([<15],'FACT_Theory Enrollment'[CYorLY] = "CY Quarter")
			VAR ThoeryLY = CALCULATE([<15],'FACT_Theory Enrollment'[CYorLY] = "LY Quarter")
			RETURN
			SWITCH(TRUE(),ThoeryCY<ThoeryLY,"Green",ThoeryCY>ThoeryLY,"Red","Black")
		lineageTag: c588281b-b081-4351-b724-18881fdd5114

	measure >45_Color =
			
			VAR ThoeryCY = CALCULATE([>45],'FACT_Theory Enrollment'[CYorLY] = "CY Quarter")
			VAR ThoeryLY = CALCULATE([>45],'FACT_Theory Enrollment'[CYorLY] = "LY Quarter")
			RETURN
			SWITCH(TRUE(),ThoeryCY<ThoeryLY,"Green",ThoeryCY>ThoeryLY,"Red","Black")
		lineageTag: b87090a5-93b8-4462-9917-c1318042789a

	column STUDENT_COUNT
		dataType: int64
		formatString: 0
		lineageTag: ea2b5898-d499-4b40-8d9d-09ead8787650
		summarizeBy: sum
		sourceColumn: STUDENT_COUNT

		annotation SummarizationSetBy = Automatic

	column CRS_NAME
		dataType: string
		lineageTag: 35c16213-40c9-41d0-9c9b-2bf0394cfd98
		summarizeBy: none
		sourceColumn: CRS_NAME

		annotation SummarizationSetBy = Automatic

	column SEC_NAME
		dataType: string
		lineageTag: 29cb65cd-fc80-4744-a89b-20f7b09cb302
		summarizeBy: none
		sourceColumn: SEC_NAME

		annotation SummarizationSetBy = Automatic

	column STC_TERM
		dataType: string
		lineageTag: b714de77-b048-4812-ba9c-fdf079dfed18
		summarizeBy: none
		sourceColumn: STC_TERM

		annotation SummarizationSetBy = Automatic

	column COURSE_LOCATION
		dataType: string
		lineageTag: 943942c4-14af-49b7-b925-ce09beba3569
		summarizeBy: none
		sourceColumn: COURSE_LOCATION

		annotation SummarizationSetBy = Automatic

	column LESS_THAN_15
		dataType: int64
		formatString: 0
		lineageTag: 4e712397-eed2-4b3d-8b0b-65a64dbbb4b8
		summarizeBy: sum
		sourceColumn: LESS_THAN_15

		annotation SummarizationSetBy = Automatic

	column MORE_THAN_45
		dataType: int64
		formatString: 0
		lineageTag: 78459535-5c73-4de4-a0fd-d203375fcfb4
		summarizeBy: sum
		sourceColumn: MORE_THAN_45

		annotation SummarizationSetBy = Automatic

	column CYorLY
		dataType: string
		lineageTag: cea6490b-f4c2-48ab-8d1e-d7ad21a0fc10
		summarizeBy: none
		sourceColumn: CYorLY

		annotation SummarizationSetBy = Automatic

	column 'Qtr Header' =
			VAR QuarterNumber = SWITCH(RIGHT([STC_TERM],3),"WIQ","4","FAQ","3","SPQ","1","SUQ","4")
			RETURN
			"QTR " & QuarterNumber & " " & LEFT([STC_TERM],4)
		lineageTag: 673642ea-1cc9-476b-a50d-5d4411bab970
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'FACT_Theory Enrollment' = m
		mode: import
		queryGroup: Academics
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "coll18_repl_production", [Query="DECLARE @LASTYEAR DATE = DATEADD(YEAR, -1, GETDATE());#(lf)#(lf)WITH ACCEPTABLE_TERMS AS#(lf)#(tab)(#(lf)#(tab)#(tab)SELECT CASE WHEN GETDATE() BETWEEN CT.TERM_START_DATE AND CT.TERM_END_DATE#(lf)#(tab)#(tab)THEN CT.TERMS_ID#(lf)#(tab)#(tab)ELSE PT.PREV_TERM END TERM_TO_BE_USED,#(lf)#(tab)#(tab)'CY Quarter' CYorLY#(lf)#(tab)#(tab)FROM TERMS CT#(lf)#(tab)#(tab)INNER JOIN (#(lf)#(tab)#(tab)#(tab)SELECT  TERMS_ID,#(lf)#(tab)#(tab)#(tab)LAG(TERMS_ID) OVER (ORDER BY TERM_START_DATE) PREV_TERM, #(lf)#(tab)#(tab)#(tab) LAG(TERM_END_DATE) OVER (ORDER BY TERM_START_DATE) PREV_END_DATE#(lf)#(tab)#(tab)#(tab)FROM TERMS#(lf)#(tab)#(tab)#(tab)WHERE RIGHT(TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)#(tab)#(tab))PT ON CT.TERMS_ID = PT.TERMS_ID#(lf)#(tab)#(tab)WHERE RIGHT(CT.TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)AND GETDATE() BETWEEN PT.PREV_END_DATE AND CT.TERM_END_DATE#(lf)UNION#(lf)#(tab)#(tab)SELECT CASE WHEN @LASTYEAR BETWEEN CT.TERM_START_DATE AND CT.TERM_END_DATE#(lf)#(tab)#(tab)THEN CT.TERMS_ID#(lf)#(tab)#(tab)ELSE PT.PREV_TERM END TERM_TO_BE_USED,#(lf)#(tab)#(tab)'LY Quarter' CYorLY#(lf)#(tab)#(tab)FROM TERMS CT#(lf)#(tab)#(tab)INNER JOIN (#(lf)#(tab)#(tab)#(tab)SELECT  TERMS_ID,#(lf)#(tab)#(tab)#(tab)LAG(TERMS_ID) OVER (ORDER BY TERM_START_DATE) PREV_TERM, #(lf)#(tab)#(tab)#(tab) LAG(TERM_END_DATE) OVER (ORDER BY TERM_START_DATE) PREV_END_DATE#(lf)#(tab)#(tab)#(tab)FROM TERMS#(lf)#(tab)#(tab)#(tab)WHERE RIGHT(TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)#(tab)#(tab))PT ON CT.TERMS_ID = PT.TERMS_ID#(lf)#(tab)#(tab)WHERE RIGHT(CT.TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)AND @LASTYEAR BETWEEN PT.PREV_END_DATE AND CT.TERM_END_DATE#(lf)#(tab))#(lf)#(lf)SELECT#(lf)       COUNT(*) AS STUDENT_COUNT,#(lf)       C.CRS_NAME,#(lf)       CS.SEC_NAME,#(lf)       SAC.STC_TERM,#(lf)       COALESCE(CS.SEC_LOCATION,SCS.SCS_LOCATION, 'OTHER') AS COURSE_LOCATION,#(lf)#(tab)   CASE WHEN COUNT(*) < 15 THEN 1 ELSE 0 END AS LESS_THAN_15,#(lf)#(tab)   CASE WHEN COUNT(*) > 45 THEN 1 ELSE 0 END AS MORE_THAN_45,#(lf)#(tab)   CYorLY#(lf)FROM  #(lf)       STUDENT_ACAD_CRED SAC#(lf)JOIN STUDENT_COURSE_SEC SCS ON SAC.STUDENT_ACAD_CRED_ID = SCS.SCS_STUDENT_ACAD_CRED     #(lf)JOIN STC_STATUSES STC_S ON SAC.STUDENT_ACAD_CRED_ID = STC_S.STUDENT_ACAD_CRED_ID AND STC_S.POS = 1      #(lf)JOIN COURSE_SECTIONS CS ON CS.COURSE_SECTIONS_ID = SCS.SCS_COURSE_SECTION #(lf)JOIN SEC_STATUSES SEC_S ON CS.COURSE_SECTIONS_ID = SEC_S.COURSE_SECTIONS_ID AND SEC_S.POS = 1  #(lf)JOIN COURSES C ON CS.SEC_COURSE = C.COURSES_ID #(lf)JOIN ACCEPTABLE_TERMS T ON T.TERM_TO_BE_USED = SAC.STC_TERM#(lf)WHERE 1=1#(lf)AND CS.SEC_SUBJECT IN ('NU','NUR','NSG','BSL')        #(lf)AND SEC_S.SEC_STATUS IN ('A','N')#(lf)AND STC_S.STC_STATUS IN ('A','N')#(lf)AND RIGHT(C.CRS_NAME,1) NOT IN ('C','L')#(lf)GROUP BY     #(lf)       CS.SEC_NAME,#(lf)       C.CRS_NAME,#(lf)       SAC.STC_TERM,#(lf)       COALESCE(CS.SEC_LOCATION,SCS.SCS_LOCATION, 'OTHER'),#(lf)#(tab)#(tab)CYorLY#(lf)HAVING       #(lf)       (COUNT(*) < 15 OR COUNT(*) > 45)"])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

