table 'FACT_ReAdmits Current'
	lineageTag: 21dfbab0-b5d5-4d6d-b142-fd0e7556a739

	measure Readmission_Code = IF([Readmissioncount]>[ReAdmits_Budget], "#00B050","#C81515")
		lineageTag: 4594f0b6-1953-4543-8318-88497708411e

	measure Readmission_Flag =
			IF([Readmissioncount]>'FACT_ReAdmits Budget'[ReAdmits_Budget], UNICHAR(9650), UNICHAR(9660))
			
			// "🔺","🔻")
		lineageTag: 70d09093-6b57-41b2-8539-67028e207cbe

	measure Readmissioncount = DISTINCTCOUNT('FACT_ReAdmits Current'[STUDENT_PROGRAMS_ID])+0
		formatString: 0
		lineageTag: 2a7db294-db40-40f7-b500-b35535a36975

	column STUDENT_PROGRAMS_ID
		dataType: string
		lineageTag: 311e057a-9192-4446-aca6-efc031d68e68
		summarizeBy: none
		sourceColumn: STUDENT_PROGRAMS_ID

		annotation SummarizationSetBy = Automatic

	column STPR_LOCATION
		dataType: string
		lineageTag: 7438dc5c-1e7c-4d58-a6eb-22b9b141dcd3
		summarizeBy: none
		sourceColumn: STPR_LOCATION

		annotation SummarizationSetBy = Automatic

	column STPR_START_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: eabd3902-8c34-4ba4-ba1d-101670eed23d
		summarizeBy: none
		sourceColumn: STPR_START_DATE

		variation Variation
			isDefault
			relationship: 70f8a717-0f62-466e-9b58-67b8a777adf2
			defaultHierarchy: LocalDateTable_8d89ed37-5ce7-4de2-a42a-d3026bb073d1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STPR_END_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: e9603a28-25cd-4f18-85f3-cda29a53db74
		summarizeBy: none
		sourceColumn: STPR_END_DATE

		variation Variation
			isDefault
			relationship: c8310383-3a1b-4d36-af2c-60ddc4d60689
			defaultHierarchy: LocalDateTable_81074906-ba5b-49c0-9f61-f460b57d8100.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STPR_STATUS
		dataType: string
		lineageTag: 06fc7583-e36f-4656-830b-a1fe3a384326
		summarizeBy: none
		sourceColumn: STPR_STATUS

		annotation SummarizationSetBy = Automatic

	column PROGRAM_ID
		dataType: string
		lineageTag: 855c0d4c-cbbc-4cf5-ba47-7f768a65cc13
		summarizeBy: none
		sourceColumn: PROGRAM_ID

		annotation SummarizationSetBy = Automatic

	column STPR_ADMIT_STATUS
		dataType: string
		lineageTag: e5f06739-3927-41f8-b35d-0b99d4c88f58
		summarizeBy: none
		sourceColumn: STPR_ADMIT_STATUS

		annotation SummarizationSetBy = Automatic

	column STUDENT_ID
		dataType: string
		lineageTag: 1a50db49-f6f2-4a4f-b316-09763eca5955
		summarizeBy: none
		sourceColumn: STUDENT_ID

		annotation SummarizationSetBy = Automatic

	partition 'FACT_ReAdmits Current' = m
		mode: import
		queryGroup: Students
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "coll18_repl_production", [Query="DECLARE @CURRENTDATE DATE = GETDATE();#(lf)DROP TABLE IF EXISTS #CURRENT_TERM_READMITS, #TERMS_GROUND, #TERMS_ONLINE#(lf)#(lf)#(lf)SELECT CASE WHEN @CURRENTDATE BETWEEN CT.TERM_START_DATE AND CT.TERM_END_DATE#(lf)        THEN CT.TERMS_ID#(lf)        ELSE PT.PREV_TERM END TERM_TO_BE_USED,#(lf)        CASE WHEN @CURRENTDATE BETWEEN CT.TERM_START_DATE AND CT.TERM_END_DATE#(lf)        THEN CT.TERM_START_DATE#(lf)        ELSE PT.PREV_START_DATE END TERM_START_DATE_TO_BE_USED,#(lf)        CASE WHEN @CURRENTDATE BETWEEN CT.TERM_START_DATE AND CT.TERM_END_DATE#(lf)        THEN CT.TERM_END_DATE#(lf)        ELSE PT.PREV_END_DATE END TERM_END_DATE_TO_BE_USED#(lf)INTO #TERMS_GROUND#(lf)        FROM TERMS CT#(lf)        INNER JOIN (#(lf)            SELECT  TERMS_ID,#(lf)            LAG(TERMS_ID) OVER (ORDER BY TERM_START_DATE) PREV_TERM,#(lf)             LAG(TERM_END_DATE) OVER (ORDER BY TERM_START_DATE) PREV_END_DATE,#(lf)             LAG(TERM_START_DATE) OVER (ORDER BY TERM_START_DATE) PREV_START_DATE#(lf)            FROM TERMS#(lf)            WHERE RIGHT(TERMS_ID, 1) = 'Q'#(lf)                )PT ON CT.TERMS_ID = PT.TERMS_ID#(lf)        WHERE RIGHT(CT.TERMS_ID, 1) = 'Q'#(lf)        AND @CURRENTDATE BETWEEN PT.PREV_END_DATE AND CT.TERM_END_DATE#(lf)#(lf)#(lf)        SELECT TERMS_ID TERM_TO_BE_USED, TERM_START_DATE TERM_START_DATE_TO_BE_USED, TERM_END_DATE TERM_END_DATE_TO_BE_USED#(lf)INTO #TERMS_ONLINE#(lf)        FROM TERMS#(lf)        WHERE @CURRENTDATE BETWEEN TERM_START_DATE AND TERM_END_DATE#(lf)          AND RIGHT(TERMS_ID, 1) <> 'Q'#(lf)#(lf)#(lf)--SELECT DISTINCT STUDENT_PROGRAMS_ID,STPR_LOCATION,#(lf)--STPR_START_DATE, STPR_END_DATE#(lf)--,STPR_STATUS#(lf)--,STPR_ADMIT_STATUS#(lf)--,PROGRAM_ID#(lf)--INTO #OG#(lf)--FROM (#(lf)--SELECT SP.STUDENT_PROGRAMS_ID,SP.STPR_LOCATION,#(lf)--SPD.STPR_START_DATE, SPD.STPR_END_DATE#(lf)--,SPS.STPR_STATUS#(lf)--,SP.STPR_ADMIT_STATUS#(lf)--,T.TERM_TO_BE_USED TERMS_ID#(lf)--,RIGHT(SP.STUDENT_PROGRAMS_ID, LEN(SP.STUDENT_PROGRAMS_ID) - 8) PROGRAM_ID#(lf)--FROM STUDENT_PROGRAMS SP#(lf)--INNER JOIN STPR_DATES SPD ON SP.STUDENT_PROGRAMS_ID = SPD.STUDENT_PROGRAMS_ID AND SPD.POS = 1#(lf)--INNER JOIN STPR_STATUSES SPS ON SP.STUDENT_PROGRAMS_ID = SPS.STUDENT_PROGRAMS_ID AND SPS.POS = 1#(lf)--INNER JOIN #TERMS_GROUND  T ON SPD.STPR_START_DATE BETWEEN T.TERM_START_DATE_TO_BE_USED AND T.TERM_END_DATE_TO_BE_USED#(lf)--WHERE SPS.STPR_STATUS IN ('A')#(lf)--AND STPR_ADMIT_STATUS = 'RE'#(lf)--AND STPR_LOCATION <> 'ONL'#(lf)--UNION#(lf)--SELECT SP.STUDENT_PROGRAMS_ID,SP.STPR_LOCATION,#(lf)--SPD.STPR_START_DATE, SPD.STPR_END_DATE#(lf)--,SPS.STPR_STATUS#(lf)--,SP.STPR_ADMIT_STATUS#(lf)--,T.TERM_TO_BE_USED TERMS_ID#(lf)--,RIGHT(SP.STUDENT_PROGRAMS_ID, LEN(SP.STUDENT_PROGRAMS_ID) - 8) PROGRAM_ID#(lf)--FROM STUDENT_PROGRAMS SP#(lf)--INNER JOIN STPR_DATES SPD ON SP.STUDENT_PROGRAMS_ID = SPD.STUDENT_PROGRAMS_ID AND SPD.POS = 1#(lf)--INNER JOIN STPR_STATUSES SPS ON SP.STUDENT_PROGRAMS_ID = SPS.STUDENT_PROGRAMS_ID AND SPS.POS = 1#(lf)--INNER JOIN #TERMS_ONLINE T ON SPD.STPR_START_DATE BETWEEN T.TERM_START_DATE_TO_BE_USED AND T.TERM_END_DATE_TO_BE_USED#(lf)--WHERE SPS.STPR_STATUS IN ('A')#(lf)--AND STPR_ADMIT_STATUS = 'RE'#(lf)--AND STPR_LOCATION = 'ONL') A#(lf)#(lf)#(lf)#(lf)#(lf)SELECT SP.STUDENT_PROGRAMS_ID#(lf),LEFT(SP.STUDENT_PROGRAMS_ID, 7) STUDENT_ID#(lf),SP.STPR_LOCATION#(lf),SPD.STPR_START_DATE#(lf),SPD.STPR_END_DATE#(lf),SPS.STPR_STATUS#(lf),SP.STPR_ADMIT_STATUS#(lf),RIGHT(SP.STUDENT_PROGRAMS_ID, LEN(SP.STUDENT_PROGRAMS_ID) - 8) PROGRAM_ID#(lf)INTO #CURRENT_TERM_READMITS#(lf)FROM STUDENT_PROGRAMS SP#(lf)INNER JOIN STPR_DATES SPD ON SP.STUDENT_PROGRAMS_ID = SPD.STUDENT_PROGRAMS_ID AND SPD.POS = 1#(lf)INNER JOIN STPR_STATUSES SPS ON SP.STUDENT_PROGRAMS_ID = SPS.STUDENT_PROGRAMS_ID AND SPS.POS = 1#(lf)WHERE SPS.STPR_STATUS IN ('A')#(lf)AND STPR_ADMIT_STATUS = 'RE'#(lf)AND STPR_START_DATE IN (#(lf)SELECT TERM_START_DATE_TO_BE_USED#(lf)FROM #TERMS_GROUND#(lf)UNION#(lf)SELECT TERM_START_DATE_TO_BE_USED#(lf)FROM #TERMS_ONLINE#(lf))#(lf)#(lf)SELECT * FROM #CURRENT_TERM_READMITS#(lf)#(lf)"])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

