table 'FACT_Satisfaction >2024'
	lineageTag: 803dccfc-36f1-4a3e-b7c7-18faedddb574

	measure Invites = CALCULATE(COUNT('FACT_Satisfaction >2024'[courseSectionTotalEnrolled]))
		formatString: 0
		lineageTag: 15bd5d67-6d31-4f84-ac16-7b570caacb6d

	measure MinReponsePerCourse_Qualtrics =
			
			CALCULATE(
			    MIN('FACT_Satisfaction >2024'[courseSectionTotalEnrolled]),
			    ALLEXCEPT('FACT_Satisfaction >2024', 'FACT_Satisfaction >2024'[CourseId_TermId])
			)
		lineageTag: d8c3d357-6a06-48f2-8db1-a4d6dfa2af21

	measure ResponseRateQualtrics = CALCULATE(DIVIDE(COUNT('FACT_Satisfaction >2024'[ResponseId]), [NbrOfInvitesQualtrics_QTR],0),DIM_Terms[CurrentYearCompletedQuarterFlag]=1)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2d53b018-c7e4-4726-9c6d-042a11e4f88c

	measure NbrOfInvitesQualtrics_QTR =
			CALCULATE(
			SUMX(
			    VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			    [MinReponsePerCourse_Qualtrics]
			),DIM_Terms[CurrentYearCompletedQuarterFlag]=1)+0
		formatString: 0
		lineageTag: 012986b4-1bcf-4288-b1ca-111595b8e8f3

	measure ResponseID_count_QTR = CALCULATE(COUNT('FACT_Satisfaction >2024'[ResponseId]),DIM_Terms[CurrentYearCompletedQuarterFlag]=1)+0
		formatString: 0
		lineageTag: 9a0cddf8-46d3-494f-97c3-d953fb7277c8

	measure ResponseQuarterVariance = ([ResponseRateQualtrics]-[Response_Rate_QTR_2024_ON]+0) *100
		formatString: 0.0
		lineageTag: c687d82e-3284-4a06-9ed1-febb96710677

	measure ResponseID_count_YTD = CALCULATE(COUNT('FACT_Satisfaction >2024'[ResponseId]),DIM_Terms[YTDFlag_demographics]=1)+0
		formatString: 0
		lineageTag: 15bb6f6f-b393-492a-8fc7-1fe24177a0a2

	measure NbrOfInvitesQualtrics_YTD =
			CALCULATE(
			SUMX(
			    VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			    [MinReponsePerCourse_Qualtrics]
			),DIM_Terms[YTDFlag_demographics]=1)+0
		formatString: 0
		lineageTag: 694000c1-6857-419d-bf0f-3be824a71d3f

	measure ResponseYTDVariance = DIVIDE([ResponseID_count_YTD],[NbrOfInvitesQualtrics_YTD],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 910f6ec5-e7f5-4932-bbde-7c303ef4669f

	measure ResponseYTDL/YTDVariance = ([ResponseYTDVariance]-[Response_Rate_LYTD_2024_ON]+0) *100
		formatString: 0.00
		lineageTag: 894f697a-44be-4953-84da-cee8dc7522c1

	measure YTD_Lable = ```
			
			VAR YTDYear = 
			    CALCULATE(
			        YEAR(MIN(DIM_Terms[TERM_START_DATE])),
			        FILTER(
			            DIM_Terms, 
			            DIM_Terms[YTDFlag_demographics] = 1
			        )
			    )
			RETURN
			IF(
			    NOT(ISBLANK(YTDYear)),
			    "YTD " & YTDYear,
			    BLANK()
			)
			```
		lineageTag: 13d82e00-7a38-42e1-aaa4-23ba278e3662

	measure Recommand_CYQTR% = ```
			
			var Num = CALCULATE([ResponseID_count_QTR],ALLSELECTED('Dim Recommend Galen'))
			RETURN
			 "(" & FORMAT([ResponseID_count_QTR]/Num, "0%") & ")"
			
			```
		lineageTag: 35c23c11-45a5-42e9-b7dc-fce73ce3734c

	measure 'QTR to QTR' =
			
			
			var CYNum = CALCULATE([ResponseID_count_QTR],ALLSELECTED('Dim Recommend Galen'))
			Var CYQTR = [ResponseID_count_QTR]/CYNum
			var LYNum = CALCULATE([Response_Count_LYQTR_2024_ON],ALLSELECTED('Dim Recommend Galen'))
			Var LYQTR = [Response_Count_LYQTR_2024_ON]/LYNum
			 RETURN
			CYQTR- LYQTR
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: e34f82aa-f07d-4df0-81ed-2c1a97289e67

	measure Recommand_CYTD% = ```
			
			var Num = CALCULATE([ResponseID_count_YTD],ALLSELECTED('Dim Recommend Galen'))
			RETURN
			 "(" & FORMAT([ResponseID_count_YTD]/Num, "0%") & ")"
			
			```
		lineageTag: e4a5968f-56ca-48b1-a6fd-e756b1c9b616

	measure Enrolled_CYQTR = CALCULATE(MAX('FACT_Satisfaction >2024'[courseSectionTotalEnrolled]),DIM_Terms[CurrentYearCompletedQuarterFlag]=1)+0
		formatString: 0
		lineageTag: 4365f123-496f-40fa-aa8f-b3804e4341b4

	measure Surveyed_CYQTR_FInal = SUMX(VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),[Enrolled_CYQTR])
		formatString: 0
		lineageTag: b71f4d71-0ba0-4ccd-ab30-631d8b238f4f

	measure Enrolled_CYTD = CALCULATE(MAX('FACT_Satisfaction >2024'[courseSectionTotalEnrolled]),DIM_Terms[YTDFlag_demographics]=1)+0
		formatString: 0
		lineageTag: b7be0f92-32f4-4b31-bef6-0c9966df183e

	measure Surveyed_CYTD_FInal = SUMX(VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),[Enrolled_CYTD])
		formatString: 0
		lineageTag: 089a665f-1596-4093-bc3d-27db46c1d038

	measure Response_CYQTR = ```
			
			    CALCULATE(
			        COUNT('FACT_Satisfaction >2024'[CourseId_TermId]),
			        DIM_Terms[CurrentYearCompletedQuarterFlag] = 1
			    )
			```
		formatString: 0
		lineageTag: f8daf11e-75cf-47c1-b992-63f8967f94b9

	measure Response_CYTD = ```
			
			VAR Enrolled = 
			    CALCULATE(
			        COUNT('FACT_Satisfaction >2024'[CourseId_TermId]),
			        DIM_Terms[YTDFlag_demographics] = 1
			    )
			RETURN
			Enrolled
			```
		formatString: 0
		lineageTag: 6212544d-fd5a-4979-a79c-fbe29537b44a

	measure Response_CYQTR% = CALCULATE([Response_CYQTR] / [Surveyed_CYQTR_FInal])
		lineageTag: 2651843e-723d-4fb4-8e17-5edc9c2ebfdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Response_CYTD% = CALCULATE([Response_CYTD] / [Surveyed_CYTD_FInal])
		lineageTag: 21fb5a2e-eef6-4a2e-8744-8b699563dad7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ResponseRateCY =
			COALESCE(
			    CALCULATE(
			        DIVIDE(COUNT('FACT_Satisfaction >2024'[ResponseId]), [NbrOfInvitesQualtrics_QTR], 0),
			        DIM_Terms[CurrentYearCompletedQuarterFlag] = 1
			    ),
			    0
			)
			
			//CALCULATE(DIVIDE(COUNT('FACT_Satisfaction >2024'[ResponseId]), [NbrOfInvitesQualtrics_QTR],0),DIM_Terms[CurrentYearCompletedQuarterFlag]=1)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 73abf1d6-1099-45f4-8e89-7d00b0149892

	measure Recommand_CYQTR2% =
			
			var Num = CALCULATE([ResponseID_count_QTR],ALLSELECTED('Dim Recommend Galen'))
			RETURN
			 [ResponseID_count_QTR]/Num
		lineageTag: 3fe84783-6203-49c2-8de8-0147890867d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Response_Count_LYTD_2024_ON = ```
			
			COALESCE(
			    CALCULATE(
			        COUNT('FACT_Satisfaction <2024'[Response]), 
			        DIM_Terms[LastYearYTDFlag_Satisfaction] = 1
			    ),
			    CALCULATE(
			        COUNT('FACT_Satisfaction >2024'[CourseId_TermId]), 
			        DIM_Terms[LastYearYTDFlag_Satisfaction] = 1
			    )
			) + 0
			
			// CALCULATE(COUNT('FACT_Satisfaction >2024'[CourseId_TermId]),DIM_Terms[LastYearYTDFlag_Satisfaction]=1)+0
			```
		formatString: 0
		lineageTag: 8ca3e2e4-f158-47e0-a87f-cf433169fb08

	measure surveyed_LYTD_Final_2024_on = ```
			COALESCE(
			    COALESCE(
			        SUMX(
			            VALUES('FACT_Satisfaction <2024'[Course_Section_Id]),
			            [Enrolled_LYTD]
			        ),
			        SUMX(
			            VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			            [Enrolled_LYTD_2024_ON]
			        )
			    ),
			    0
			)
			
			// COALESCE(
			//     SUMX(
			//         VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			//         [Enrolled_LYTD_2024_ON]
			//     ),
			//     0
			// )
			
			
			```
		formatString: 0
		lineageTag: 702f5e97-280a-4bab-a487-0e8080304304

	measure Enrolled_LYQTR_2024_ON = ```
			CALCULATE(MAX('FACT_Satisfaction >2024'[courseSectionTotalEnrolled]),DIM_Terms[PreviousYearCompletedQuarter]=1)
			
			```
		formatString: 0
		lineageTag: 821b3358-3485-4067-9835-98cd2ed0d469

	measure Enrolled_LYTD_2024_ON = ```
			CALCULATE(MAX('FACT_Satisfaction >2024'[courseSectionTotalEnrolled]),DIM_Terms[LastYearYTDFlag_Satisfaction]=1)
			
			```
		formatString: 0
		lineageTag: 2118eeb1-4c05-4f5f-af01-2b066784e5ab

	measure Response_LYTD%_2024_ON = CALCULATE([Response_Count_LYTD_2024_ON] / [surveyed_LYTD_Final_2024_on])
		lineageTag: aa7e8c38-fe32-4b75-b234-ede2999b0673

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Recommand_LYTD%_2024_ON =
			
			var Num = CALCULATE([Response_Count_LYTD_2024_ON],ALLSELECTED('Dim Recommend Galen'))
			RETURN
			 "(" & FORMAT([Response_Count_LYTD_2024_ON]/Num, "0%") & ")"
		lineageTag: 148788b8-1146-4e52-8349-acef15098a0f

	measure Response_Count_LYQTR_2024_ON = ```
			
			COALESCE(
			    CALCULATE(
			        COUNT('FACT_Satisfaction >2024'[CourseId_TermId]), 
			        DIM_Terms[PreviousYearCompletedQuarter] = 1
			    ),
			    CALCULATE(
			        COUNT('FACT_Satisfaction <2024'[Response]), 
			        DIM_Terms[PreviousYearCompletedQuarter] = 1
			    )
			    
			) + 1
			
			
			//CALCULATE(COUNT('FACT_Satisfaction >2024'[CourseId_TermId]),DIM_Terms[PreviousYearCompletedQuarter]=1)+0
			
			```
		formatString: 0
		lineageTag: adfef428-b637-4de7-98d0-32c848365ed7

	measure Surveyed_LYQTR_FInal_2024_ON =
			COALESCE(
			    COALESCE(
			        SUMX(
			            VALUES('FACT_Satisfaction <2024'[Course_Section_Id]),
			            [Enrolled_LYQTR]
			        ),
			        SUMX(
			            VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			            [Enrolled_LYQTR_2024_ON]
			        )
			    ),
			    0
			)
			
			
			//COALESCE(
			//     SUMX(
			//         VALUES('FACT_Satisfaction <2024'[Course_Section_Id]),
			//         [Enrolled_LYQTR]
			//     ),
			//     SUMX(
			//         VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			//         [Enrolled_LYQTR_2024_ON]
			//     )
			// )
			
			//SUMX(VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),[Enrolled_LYQTR_2024_ON])
		formatString: 0
		lineageTag: ec0e0c16-8784-437d-ac17-eb5102e9c52c

	measure Response_LYQTR%_2024_ON = CALCULATE([Response_Count_LYQTR_2024_ON] / [Surveyed_LYQTR_FInal_2024_ON])
		lineageTag: 3d302628-8921-41f0-aa99-1bf46d3f34b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CYQTR-LYQTR_variance_2024_ON = [Response_CYQTR%]-[Response_LYQTR%_2024_ON]
		lineageTag: 0e2e401e-a5ee-4de0-902b-36821d9efde7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CYTD-LYTD_variance_2024_ON = [Response_CYTD%]-[Response_LYTD%_2024_ON]
		lineageTag: 81bcbc62-4ce4-4d71-a4c3-b639831b6f48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinReponsePerCourse_2024_ON = ```
			
			CALCULATE(
			    COALESCE(
			        MIN('FACT_Satisfaction >2024'[courseSectionTotalEnrolled]), 
			        0  
			    ),
			    ALLEXCEPT(
			        'FACT_Satisfaction >2024', 
			        'FACT_Satisfaction >2024'[CourseId_TermId]
			        // 'FACT_Satisfaction >2024'[studentProgram], 
			        // 'FACT_Satisfaction >2024'[termId], 
			        // 'FACT_Satisfaction >2024'[studentProgramCampus]
			    // ),
			     //DIM_Terms[Is_Last_Year_Today_Between] = "TRUE"
			)
			
			)
			```
		formatString: 0
		lineageTag: 37260863-9aba-45d1-97c6-9d534f8ce267

	measure NbrOfInvites_LYQTR_2024_ON = ```
			
			COALESCE(
			    CALCULATE(
			        SUMX(
			            VALUES('FACT_Satisfaction <2024'[COURSE_SECTIONS_ID]),
			            [MinReponsePerCourse]
			        ),
			        DIM_Terms[PreviousYearCompletedQuarter] = 1
			    ),
			    CALCULATE(
			        SUMX(
			            VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			            [MinReponsePerCourse_2024_ON]
			        ),
			        DIM_Terms[PreviousYearCompletedQuarter] = 1
			    )
			) + 0
			
			// CALCULATE(SUMX(
			//     VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			//     [MinReponsePerCourse_2024_ON]
			// ),DIM_Terms[PreviousYearCompletedQuarter]=1)+0
			
			
			```
		formatString: 0
		lineageTag: 743bf9b2-4479-478e-a793-d1eadc0df784

	measure Response_Rate_QTR_2024_ON = ```
			DIVIDE([Response_Count_LYQTR_2024_ON],[Surveyed_LYQTR_FInal_2024_ON],0)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 48eb8603-b04b-4d72-83ed-44a7ae7a04e4

	measure Response_Rate_LYTD_2024_ON = DIVIDE([Response_Count_LYTD_2024_ON],[surveyed_LYTD_Final_2024_on],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 96d98305-1d0d-4d09-bcab-1e372c0865eb

	measure Response_QTR_Flag_2024_ON = IF([ResponseRateQualtrics]>[Response_Rate_QTR_2024_ON], UNICHAR(9650), UNICHAR(9660))
		lineageTag: 77d0cd17-74f3-41ce-bc2d-33de7ba4e583

	measure Responseratecolor_2024_ON = IF([ResponseRateQualtrics]>[Response_Rate_QTR_2024_ON], "#00B050", "#C81515")
		lineageTag: 835e9129-1e57-42b2-ac11-452f77809c4a

	measure Response_YTD_Flag_2024_ON = IF([ResponseYTDVariance]>[Response_Rate_LYTD_2024_ON], UNICHAR(9650), UNICHAR(9660))
		lineageTag: 35ebb352-cb0a-4983-8e7d-a99dc5baebe3

	measure Response_YTD_color_2024_ON = IF([ResponseYTDVariance]>[Response_Rate_LYTD_2024_ON], "#00B050", "#C81515")
		lineageTag: 65da28d0-b52f-438d-bd38-9c2925bd489e

	measure LYTD_Label_2024_ON = ```
			
			VAR YTDYear = 
			    CALCULATE(
			        YEAR(MIN(DIM_Terms[TERM_START_DATE])),
			        FILTER(
			            DIM_Terms, 
			            DIM_Terms[LastYearYTDFlag_Satisfaction] = 1
			        )
			    )
			RETURN
			IF(
			    NOT(ISBLANK(YTDYear)),
			    "YTD " & YTDYear,
			    BLANK()
			)
			```
		lineageTag: 90c039a0-2e4c-4143-b4ab-80fde92b0318

	measure NbrOfInvites_LYTD_2024_ON = ```
			
			CALCULATE(SUMX(
			    VALUES('FACT_Satisfaction >2024'[CourseId_TermId]),
			    [MinReponsePerCourse_2024_ON]
			),DIM_Terms[LastYearYTDFlag]=1)+0
			
			```
		formatString: 0
		lineageTag: 19ac72e7-3017-4cf2-a046-06b4f1d12269

	measure Recommand_LYQTR%_2024_ON =
			
			var Num = CALCULATE([Response_Count_LYQTR_2024_ON],ALLSELECTED('Dim Recommend Galen'))
			RETURN
			 "(" & FORMAT([Response_Count_LYQTR_2024_ON]/Num, "0%") & ")"
		lineageTag: afc6cc96-cbc7-4f63-b8df-21d64bd242dc

	measure ResponseFontColor1 = ```
			
			IF(
			    [ResponseRateCY] < [Response_Rate_LYTD_2024_ON],
			    "#C00000",  -- Dark Red
			    "#000000"   -- Black 
			)
			
			```
		lineageTag: a88f1524-9071-4000-8200-5e74ee221351

	measure Recommend_CYQTR%_For_Yes1 = ```
			
			VAR ResponseID_Yes =
			    CALCULATE(
			        [ResponseID_count_QTR],
			        'Dim Recommend Galen'[Recommend] = "Yes"
			    )
			VAR ResponseID_All =
			    CALCULATE(
			        [ResponseID_count_QTR],
			        ALLSELECTED('Dim Recommend Galen')
			    )
			RETURN
			DIVIDE(ResponseID_Yes, ResponseID_All, 0)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 0c88ed28-10bf-449e-8fc0-3ff07717c3a7

	measure Recommend_LYTD%_For_Yes1 = ```
			
			VAR ResponseID_Yes_LYTD =
			    CALCULATE(
			        [Response_Count_LYTD_2024_ON],
			        'Dim Recommend Galen'[Recommend] = "Yes"
			    )
			VAR ResponseID_All_LYTD =
			    CALCULATE(
			        [Response_Count_LYTD_2024_ON],
			        ALLSELECTED('Dim Recommend Galen')
			    )
			RETURN
			DIVIDE(ResponseID_Yes_LYTD, ResponseID_All_LYTD,0)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 41568722-e1ec-411d-ae53-7bf840c49997

	measure SatisfactionFontColor = ```
			
			IF([Recommend_CYQTR%_For_Yes1] < [Recommend_LYTD%_For_Yes1],
			    "#C00000",  -- Dark Red
			    "#000000"   -- Black 
			)
			
			```
		lineageTag: b5041a4f-7038-480c-b22a-7417f330c7d0

	column ResponseId
		dataType: string
		lineageTag: 1f717acd-e6b9-4383-96ca-d966f893f407
		summarizeBy: none
		sourceColumn: ResponseId

		annotation SummarizationSetBy = Automatic

	column Q8
		dataType: string
		lineageTag: 39d82404-5ab6-41d4-a76e-717a34dd9812
		summarizeBy: none
		sourceColumn: Q8

		annotation SummarizationSetBy = Automatic

	column courseId
		dataType: string
		lineageTag: f30b45f0-258d-4699-9e1a-7cb564f91a0a
		summarizeBy: none
		sourceColumn: courseId

		annotation SummarizationSetBy = Automatic

	column termId
		dataType: string
		lineageTag: a6428d01-2024-4d7b-bc58-512d0e20d604
		summarizeBy: none
		sourceColumn: termId

		annotation SummarizationSetBy = Automatic

	column studentProgramRegion
		dataType: string
		lineageTag: 148f41c8-3722-408d-bcf7-616944107a91
		summarizeBy: none
		sourceColumn: studentProgramRegion

		annotation SummarizationSetBy = Automatic

	column studentProgramCampus
		dataType: string
		lineageTag: 3f741c4e-5646-47b0-9bde-91d09f99a057
		summarizeBy: none
		sourceColumn: studentProgramCampus

		annotation SummarizationSetBy = Automatic

	column studentProgramId
		dataType: string
		lineageTag: 7b7c6f39-51e6-43a6-a498-2dc07e274b18
		summarizeBy: none
		sourceColumn: studentProgramId

		annotation SummarizationSetBy = Automatic

	column studentProgram
		dataType: string
		lineageTag: 3e5017d2-5972-459e-b8d9-72b6276e0879
		summarizeBy: none
		sourceColumn: studentProgram

		annotation SummarizationSetBy = Automatic

	column courseSectionTotalEnrolled
		dataType: int64
		formatString: 0
		lineageTag: 555a77eb-d0d1-4462-b09a-56543a702783
		summarizeBy: sum
		sourceColumn: courseSectionTotalEnrolled

		annotation SummarizationSetBy = Automatic

	column CourseId_TermId = 'FACT_Satisfaction >2024'[courseId] & "_" & [termId]
		lineageTag: 79beda40-927d-4511-992a-c3b9975c8e41
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Recommend Galen' =
			
			SWITCH('FACT_Satisfaction >2024'[Q8],"1","YES","2","NO","UNKNOWN")
		lineageTag: c715dbc7-faad-4ae1-8e85-c7699ec55f89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column YTD_Flag_Stat = "YTD " & RIGHT([PreviousYearSameQuarter],4)
		lineageTag: ed550251-f894-423c-a89d-28473f34a666
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CYTD_Flag_Stat = "YTD " & RIGHT([CurrentYearCompletedQuarter],4)
		lineageTag: a573d2b0-5c34-4d5f-93ca-15bc3d56946b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column flag_gr_2024 = RELATED(DIM_Terms[PreviousYearCompletedQuarter])
		formatString: 0
		lineageTag: a94de286-ebc4-4612-87b8-2f102a382c96
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'FACT_Satisfaction >2024' = m
		mode: import
		queryGroup: Surveys
		source =
				let
				    Source = Table.Combine({SV_3lUdV2KMxHv7y98, SV_9z4UPiyMXXwmCFw, SV_aVva3lzdXYwgJ9Q, SV_3r4As4GiRrtECdE, SV_6sVhwI30Q0vBfhQ, SV_2htorCxBvOSbRzg})
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

