table FACT_TBA_Courses
	lineageTag: 5e15e951-197f-4062-a084-cae6dad430fa

	measure CurrentTermTBA = "("&CALCULATE(MIN(FACT_TBA_Courses[SEC_TERM]))&")"
		lineageTag: 810f291a-41d4-42b5-ab70-0b25a6dd90fd

	measure FutureTermTBA = "("&CALCULATE(MAX(FACT_TBA_Courses[SEC_TERM]))&")"
		lineageTag: bfdfa655-167a-441e-ac04-c47dd0f3fffe

	measure 'TBA Count' = ```
			SWITCH(TRUE(),SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Current" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Clinical",SUM(FACT_TBA_Courses[CLN_Current]),SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Current" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Lab",SUM(FACT_TBA_Courses[LAB_Current]),SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Current" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Lecture",SUM(FACT_TBA_Courses[LEC_Current]), 
			SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Future" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Clinical",SUM(FACT_TBA_Courses[CLN_Future]),SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Future" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Lab",SUM(FACT_TBA_Courses[LAB_Future]),SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Future" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Lecture",SUM(FACT_TBA_Courses[LEC_Future]),
			SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Grand Total" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Current",SUM(FACT_TBA_Courses[CLN_Current])+SUM(FACT_TBA_Courses[LAB_Current])+SUM(FACT_TBA_Courses[LEC_Current]),SELECTEDVALUE('DIM_TBA_Headers'[Header]) = "Grand Total" && SELECTEDVALUE('DIM_TBA_Headers'[Type]) = "Future",SUM(FACT_TBA_Courses[CLN_Future])+SUM(FACT_TBA_Courses[LAB_Future])+SUM(FACT_TBA_Courses[LEC_Future]),0)
			```
		formatString: 0
		lineageTag: 4275bec4-6959-4bf1-81f4-8c641b86a0d9

	measure 'Current GT' = SUM('FACT_TBA_Courses'[CLN_Current]) + SUM('FACT_TBA_Courses'[LAB_Current]) + SUM('FACT_TBA_Courses'[LEC_Current])
		formatString: 0
		lineageTag: 271e934b-8cf5-4172-be59-08284a8bbee7

	measure 'Future GT' = SUM('FACT_TBA_Courses'[CLN_Future]) + SUM('FACT_TBA_Courses'[LAB_Future]) + SUM('FACT_TBA_Courses'[LEC_Future])
		formatString: 0
		lineageTag: cb8f731c-3b41-4542-a10a-a5aa63727d08

	measure CurrentGT2 = SUM('FACT_TBA_Courses'[CLN_Current]) + SUM('FACT_TBA_Courses'[LAB_Current]) + SUM('FACT_TBA_Courses'[LEC_Current])
		formatString: 0
		lineageTag: 5b713aff-1f17-4e60-a32c-fa22cb31c10a

	measure FutureGT = SUM('FACT_TBA_Courses'[CLN_Future]) + SUM('FACT_TBA_Courses'[LAB_Future]) + SUM('FACT_TBA_Courses'[LEC_Future])
		formatString: 0
		lineageTag: b224eb6d-1907-4f1e-8173-d8fd2e93529a

	column COURSE_SECTIONS_ID
		dataType: string
		lineageTag: b5f2b8b5-e2d1-4b62-b373-e5eb82cc0fe9
		summarizeBy: none
		sourceColumn: COURSE_SECTIONS_ID

		annotation SummarizationSetBy = Automatic

	column SUBJECT
		dataType: string
		lineageTag: 41aa4fd9-ea47-42ce-ae48-5721f7ef0169
		summarizeBy: none
		sourceColumn: SUBJECT

		annotation SummarizationSetBy = Automatic

	column CSF_INSTR_METHOD
		dataType: string
		lineageTag: 8474d744-fa78-414d-bc4f-3b18a5c35f82
		summarizeBy: none
		sourceColumn: CSF_INSTR_METHOD

		annotation SummarizationSetBy = Automatic

	column INM_DESC
		dataType: string
		lineageTag: bf714264-2b12-4046-8cd5-2702e03685e7
		summarizeBy: none
		sourceColumn: INM_DESC

		annotation SummarizationSetBy = Automatic

	column SEC_TERM
		dataType: string
		lineageTag: 4ea23740-44e4-41c0-b65c-d626997c130f
		summarizeBy: none
		sourceColumn: SEC_TERM

		annotation SummarizationSetBy = Automatic

	column SEC_NAME
		dataType: string
		lineageTag: c2aa9531-ed54-4568-86ec-adf57d38fa8d
		summarizeBy: none
		sourceColumn: SEC_NAME

		annotation SummarizationSetBy = Automatic

	column CAMPUS
		dataType: string
		lineageTag: 131c1209-482e-4b05-81a3-d1f99726575f
		summarizeBy: none
		sourceColumn: CAMPUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TermType
		dataType: string
		lineageTag: 6a81278d-17b5-488b-aec9-2a4f05276ecc
		summarizeBy: none
		sourceColumn: TermType

		annotation SummarizationSetBy = Automatic

	column SEC_STATUS_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 8a1f5bda-b37a-4bea-a616-a59ef92a322f
		summarizeBy: none
		sourceColumn: SEC_STATUS_DATE

		variation Variation
			isDefault
			relationship: 8eb3d973-cc16-4772-940a-477820d91a96
			defaultHierarchy: LocalDateTable_5c20a916-098c-483f-a2a0-6551b102f5e0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SEC_STATUS
		dataType: string
		lineageTag: 2babe488-ce33-42ff-a3d6-4d5c4d21e10d
		summarizeBy: none
		sourceColumn: SEC_STATUS

		annotation SummarizationSetBy = Automatic

	column CLN_Current
		dataType: int64
		formatString: 0
		lineageTag: 5b826612-8646-4bd1-854d-bf670e65cb54
		summarizeBy: sum
		sourceColumn: CLN_Current

		annotation SummarizationSetBy = Automatic

	column LAB_Current
		dataType: int64
		formatString: 0
		lineageTag: aef53d82-606c-4e5c-bb21-029740f704e9
		summarizeBy: sum
		sourceColumn: LAB_Current

		annotation SummarizationSetBy = Automatic

	column LEC_Current
		dataType: int64
		formatString: 0
		lineageTag: 8321dea2-3f92-4090-8a5a-120c22a3ce1d
		summarizeBy: sum
		sourceColumn: LEC_Current

		annotation SummarizationSetBy = Automatic

	column CLN_Future
		dataType: int64
		formatString: 0
		lineageTag: 15a2e0e6-0b19-4d20-bfd1-8c2a81843d9e
		summarizeBy: sum
		sourceColumn: CLN_Future

		annotation SummarizationSetBy = Automatic

	column LAB_Future
		dataType: int64
		formatString: 0
		lineageTag: 255933bf-170b-4fd5-a905-0f5a61041381
		summarizeBy: sum
		sourceColumn: LAB_Future

		annotation SummarizationSetBy = Automatic

	column LEC_Future
		dataType: int64
		formatString: 0
		lineageTag: 48c09b7b-4b3d-49a5-a468-6919706a5161
		summarizeBy: sum
		sourceColumn: LEC_Future

		annotation SummarizationSetBy = Automatic

	column ClinicalCurrent = IF(([CSF_INSTR_METHOD] = "CLN" || [CSF_INSTR_METHOD] = "PREC") && FACT_TBA_Courses[TermType] = "Current", 1,0)
		formatString: 0
		lineageTag: e540eb09-5f08-4d36-86f8-b5dcb9b52ab6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Lab = IF([CSF_INSTR_METHOD] = "LAB" || [CSF_INSTR_METHOD]="VIRL", 1,0)
		formatString: 0
		lineageTag: 3a4dab4e-fb6b-4561-91c8-099b8fd81629
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Lecture = IF([CSF_INSTR_METHOD] = "LEC" || [CSF_INSTR_METHOD] = "VIRT" || [CSF_INSTR_METHOD]="OCGM" || [CSF_INSTR_METHOD] = "ONL", 1,0)
		formatString: 0
		lineageTag: bd1a9d28-32d8-4752-a7b9-89dfd309d185
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Custom
		dataType: string
		lineageTag: 4ceca60e-549d-4bc9-8b4a-da9f109ab595
		summarizeBy: none
		sourceColumn: Custom

		annotation SummarizationSetBy = Automatic

	partition FACT_TBA_Courses = m
		mode: import
		queryGroup: Academics
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "coll18_repl_production", [Query="With CurrentTerm AS (#(lf)#(tab)SELECT TOP 1 TERM_START_DATE, TERMS_ID, 'Current' TermType#(lf)#(tab)#(tab)FROM TERMS CT#(lf)#(tab)#(tab)WHERE RIGHT(CT.TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)AND GETDATE() >= TERM_START_DATE#(lf)#(tab)#(tab)ORDER BY TERM_START_DATE DESC),#(lf)FutureTerm AS( SELECT TOP 1 TERM_END_DATE, TERMS_ID, 'Future' TermType#(lf)#(tab)#(tab)FROM TERMS CT#(lf)#(tab)#(tab)WHERE RIGHT(CT.TERMS_ID, 1) = 'Q'#(lf)#(tab)#(tab)AND GETDATE() < CT.TERM_END_DATE#(lf)#(tab)#(tab)AND GETDATE() < TERM_START_DATE#(lf)#(tab)#(tab)ORDER BY TERM_END_DATE ASC),#(lf)AcceptableTerms AS (#(lf)#(tab)SELECT * FROM CurrentTerm UNION SELECT * FROM FutureTerm)#(lf)#(lf)SELECT CS.COURSE_SECTIONS_ID, SEC_SUBJECT AS SUBJECT, CSF.CSF_INSTR_METHOD, IM.INM_DESC, CS.SEC_TERM, CS.SEC_NAME,COALESCE(CS.SEC_LOCATION,'ONL') CAMPUS, T.TermType,#(lf)CASE CSF_INSTR_METHOD WHEN 'VIRL' THEN 'LAB' WHEN 'VIRT' THEN 'LEC' WHEN 'OCGM' THEN 'LEC' WHEN 'ONL' THEN 'LEC' WHEN 'PREC' THEN 'LEC' ELSE CSF_INSTR_METHOD END + '_' +TermType AS TermTypeId,#(lf)1 as CNT, S.SEC_STATUS_DATE, S.SEC_STATUS#(lf)#(tab)FROM COURSE_SECTIONS CS#(lf)#(tab)LEFT JOIN COURSE_SEC_FACULTY CSF ON CS.COURSE_SECTIONS_ID = CSF.CSF_COURSE_SECTION#(lf)#(tab)INNER JOIN INSTR_METHODS IM ON CSF.CSF_INSTR_METHOD = IM.INSTR_METHODS_ID#(lf)#(tab)INNER JOIN AcceptableTerms T ON CS.SEC_TERM = T.TERMS_ID#(lf)#(tab)INNER JOIN SEC_STATUSES S ON S.COURSE_SECTIONS_ID = CS.COURSE_SECTIONS_ID AND S.POS = 1#(lf)#(tab)LEFT JOIN PERSON P ON CSF.CSF_FACULTY = P.ID#(lf)#(tab)WHERE (CSF.CSF_FACULTY = 1122928#(lf)#(tab)OR CSF.COURSE_SEC_FACULTY_ID IS NULL)#(lf)#(tab)AND RIGHT(SEC_NO, 3) <> 'TBA'#(lf)#(lf)UNION#(lf)SELECT NULL, NULL, NULL, NULL, TERMS_ID, NULL, NULL, TermType, 'LAB_Current', 0, NULL, NULL FROM AcceptableTerms WHERE TermType = 'Current'#(lf)UNION#(lf)SELECT NULL, NULL, NULL, NULL, TERMS_ID, NULL, NULL, TermType, 'LEC_Current', 0, NULL, NULL FROM AcceptableTerms WHERE TermType = 'Current'#(lf)UNION#(lf)SELECT NULL, NULL, NULL, NULL, TERMS_ID, NULL, NULL, TermType, 'CLN_Current', 0, NULL, NULL FROM AcceptableTerms WHERE TermType = 'Current'#(lf)UNION#(lf)SELECT NULL, NULL, NULL, NULL, TERMS_ID, NULL, NULL, TermType, 'CLN_Future', 0, NULL, NULL FROM AcceptableTerms WHERE TermType = 'Future'#(lf)UNION#(lf)SELECT NULL, NULL, NULL, NULL, TERMS_ID, NULL, NULL, TermType, 'LAB_Future', 0, NULL, NULL FROM AcceptableTerms WHERE TermType = 'Future'#(lf)UNION#(lf)SELECT NULL, NULL, NULL, NULL, TERMS_ID, NULL, NULL, TermType, 'LEC_Future', 0, NULL, NULL FROM AcceptableTerms WHERE TermType = 'Future'"]),
				    #"Pivoted Column" = Table.Pivot(Source, List.Distinct(Source[TermTypeId]), "TermTypeId", "CNT", List.Sum),
				    #"Replaced Value" = Table.ReplaceValue(#"Pivoted Column",0,null,Replacer.ReplaceValue,{"CLN_Current"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",0,null,Replacer.ReplaceValue,{"LAB_Current"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",0,null,Replacer.ReplaceValue,{"LEC_Current"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",0,null,Replacer.ReplaceValue,{"CLN_Future"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",0,null,Replacer.ReplaceValue,{"LAB_Future"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4",0,null,Replacer.ReplaceValue,{"LEC_Future"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value5", "Custom", each ""),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([SEC_STATUS] = "A"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

