table 'FACT_ReAdmits Budget'
	lineageTag: 6b9ad5e7-b260-4dd3-a93f-1dff4f376d6c

	measure ReAdmits_Budget = ```
			
			VAR CurrentYear = YEAR(TODAY())
			VAR CurrentQuarter = QUARTER(TODAY())
			VAR StartMonth = (CurrentQuarter - 1) * 3 + 1
			VAR READMITS = 
			    CALCULATE(
			        SUM('FACT_ReAdmits Budget'[Value]),
			        'FACT_ReAdmits Budget'[Year] = CurrentYear,
			        SWITCH(
			            'FACT_ReAdmits Budget'[Month],
			            "January", 1,
			            "February", 2,
			            "March", 3,
			            "April", 4,
			            "May", 5,
			            "June", 6,
			            "July", 7,
			            "August", 8,
			            "September", 9,
			            "October", 10,
			            "November", 11,
			            "December", 12,
			            0  -- Default value in case of an invalid month
			        ) >= StartMonth,
			        SWITCH(
			            'FACT_ReAdmits Budget'[Month],
			            "January", 1,
			            "February", 2,
			            "March", 3,
			            "April", 4,
			            "May", 5,
			            "June", 6,
			            "July", 7,
			            "August", 8,
			            "September", 9,
			            "October", 10,
			            "November", 11,
			            "December", 12,
			            0  -- Default value in case of an invalid month
			        ) <= MONTH(TODAY())
			    )
			
			RETURN 
			IF(ISBLANK(READMITS), 0, READMITS)
			
			
			// VAR READMITS = CALCULATE(
			//     SUM('FACT_ReAdmits Budget'[Value]),
			//     'FACT_ReAdmits Budget'[Month] = FORMAT(TODAY(), "MMMM"),
			//     'FACT_ReAdmits Budget'[Year] = YEAR(TODAY())
			// )
			// RETURN 
			// IF(READMITS = BLANK(), 0, READMITS)
			```
		formatString: 0
		lineageTag: 39538947-5cb7-4a69-b192-3ab11b1a3046

	measure ReAdmits_Next_Terms = ```
			
			
			VAR March_Readmits = CALCULATE(
			    SUM('FACT_ReAdmits Budget'[Value]),
			    'FACT_ReAdmits Budget'[Month] = FORMAT(EDATE(TODAY(), 2), "MMMM"),
			    'FACT_ReAdmits Budget'[Year] = YEAR(EDATE(TODAY(), 2))
			)
			
			VAR April_Readmits = CALCULATE(
			    SUM('FACT_ReAdmits Budget'[Value]),
			    'FACT_ReAdmits Budget'[Month] = FORMAT(EDATE(TODAY(), 3), "MMMM"),
			    'FACT_ReAdmits Budget'[Year] = YEAR(EDATE(TODAY(), 3))
			)
			RETURN 
			IF(March_Readmits = BLANK(), 0, March_Readmits) + 
			IF(April_Readmits = BLANK(), 0, April_Readmits)
			
			// VAR READMITS = CALCULATE(
			//     SUM('FACT_ReAdmits Budget'[Value]),
			//     'FACT_ReAdmits Budget'[Month] = FORMAT(EDATE(TODAY(), 1), "MMMM"),
			//     'FACT_ReAdmits Budget'[Year] = YEAR(EDATE(TODAY(), 1))
			// )
			// RETURN 
			// IF(READMITS = BLANK(), 0, READMITS)
			```
		formatString: 0
		lineageTag: 405d1d56-fbac-4f55-85c5-3486ec55300a

	measure ReAdmits% = ```
			
			VAR CUR_PRE = [Readmissioncount] - 'FACT_ReAdmits Budget'[ReAdmits_Budget]
			VAR final = DIVIDE(CUR_PRE, 'FACT_ReAdmits Budget'[ReAdmits_Budget],0)
			RETURN
			    IF(
			       [Readmissioncount] > 'FACT_ReAdmits Budget'[ReAdmits_Budget],             
			        CONCATENATE("+", FORMAT(final, "0.00%")),      
			        CONCATENATE("-", FORMAT(ABS(final), "0.00%"))   
			    )
			
			```
		lineageTag: 7f49e850-e54c-45c5-8f1a-7ccd73755c0e

	measure ReAdmits_Future% = ```
			
			VAR CUR_PRE = 'FACT_ReAdmits Future'[FutureReadmissions] - 'FACT_ReAdmits Budget'[ReAdmits_Next_Terms]
			VAR final = DIVIDE(CUR_PRE, 'FACT_ReAdmits Budget'[ReAdmits_Next_Terms],0)
			RETURN
			    IF(
			       [FutureReadmissions] > 'FACT_ReAdmits Budget'[ReAdmits_Next_Terms],             
			        CONCATENATE("+", FORMAT(final, "0.00%")),      
			        CONCATENATE("-", FORMAT(ABS(final), "0.00%"))   
			    )
			
			```
		lineageTag: 4d1de23d-0a19-488f-8b9d-9fd4f24a0511

	column Campus
		dataType: string
		lineageTag: a3ea0446-25e2-40be-ad35-070a55e5b800
		summarizeBy: none
		sourceColumn: Campus

		annotation SummarizationSetBy = Automatic

	column Program
		dataType: string
		lineageTag: e76b001e-8a40-4360-bc0f-2ec236a67348
		summarizeBy: none
		sourceColumn: Program

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 616d474e-1cf7-464f-b9a0-7df1195b8144
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 0b57611c-cc25-4871-b674-901d8f79062b
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: e660af87-7f70-420f-9c11-b31c99afb788
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Period = 'FACT_ReAdmits Budget'[Year] & 'FACT_ReAdmits Budget'[Month]
		lineageTag: 56ca202a-a2cd-47ae-8914-189e1d5e30ae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Term = [Year]&SWITCH([Month],"Q1","SPQ","Q2","SUQ","Q3","FAQ","Q4","WIQ","N/A")
		lineageTag: a2558734-e794-450e-9926-fbb134087d74
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Campus_New = LOOKUPVALUE('Campus Region'[LOCATIONS_ID],'Campus Region'[LOCATIONS_ID],[Campus],"OTHER")
		lineageTag: 750b7f36-85fb-437a-bdfa-0377a8c90dc4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'HCA Indicator'
		dataType: string
		lineageTag: 3b5fed41-c8a9-4e5f-a215-757ee9657fed
		summarizeBy: none
		sourceColumn: HCA Indicator

		annotation SummarizationSetBy = Automatic

	partition 'FACT_ReAdmits Budget' = m
		mode: import
		queryGroup: Students
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://hcahealthcare.sharepoint.com/sites/HTPS-GalenCollaboration/Shared%20Documents/Project%20Folder/Executive%20Dashboards/Student%20Enrollment%20Budget.xlsx"), null, true),
				    #"Restarts - Monthly_Sheet" = Source{[Item="Restarts - Monthly",Kind="Sheet"]}[Data],
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Restarts - Monthly_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Campus", type text}, {"Program", type text}, {"HCA Indicator", type any}, {"January", Int64.Type}, {"February", type any}, {"March", type any}, {"April", Int64.Type}, {"May", type any}, {"June", type any}, {"July", Int64.Type}, {"August", type any}, {"September", type any}, {"October", Int64.Type}, {"November", type any}, {"December", type any}, {"Year", Int64.Type}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Campus", "Program", "HCA Indicator", "Year"}, "Attribute", "Value"),
				    #"Replaced Value" = Table.ReplaceValue(#"Unpivoted Columns",2024,"",Replacer.ReplaceValue,{"Value"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Attribute", "Month"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Campus", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

