table 'Official list for IT'
	lineageTag: 88ae6a03-b64d-4dda-b556-eddb90f5e93c

	column ID
		dataType: int64
		formatString: 0
		lineageTag: c5aea793-d9f7-4fad-8682-8461437e12e9
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Employee Name'
		dataType: string
		lineageTag: c80aa053-9443-484c-b8ce-24b48b08bf0a
		summarizeBy: none
		sourceColumn: Employee Name

		annotation SummarizationSetBy = Automatic

	column 'Campus Abbrev'
		dataType: string
		lineageTag: 7608babf-4aa5-43ef-b0e0-6ae3ec48aa62
		summarizeBy: none
		sourceColumn: Campus Abbrev

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 2e42fc9f-fe19-4f3e-a82c-d37bd0f16d80
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column 'Email ID' = ```
			RELATED(Operations_Emails[PERSON_EMAIL_ADDRESSES])
			
			//LOOKUPVALUE('Operations - HR'[email_address], 'Operations - HR'[person_id], FORMAT('Official list for IT'[ID], "0"))
			
			```
		lineageTag: e5f3e7c4-6dd0-4dd6-b103-3ac32d32a865
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Full ID' = 'Official list for IT'[Campus Abbrev] & 'Official list for IT'[ID]
		lineageTag: 0d2a4e78-4bc0-414a-ac97-0091013f75a4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Official list for IT' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://hcahealthcare.sharepoint.com/sites/HTPS-GalenCollaboration/Shared%20Documents/Project%20Folder/Executive%20Dashboards/Dashboard%20Permissions.xlsx"), null, true),
				    #"Official list for IT_Sheet" = Source{[Item="Official list for IT",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Official list for IT_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Employee Name", type text}, {"Campus Abbrev", type text}, {"title", type text}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"IT needs this list to drive the new regional dashboards..... Must maintain it with Carley - this is my copy.", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column5", "Column6", "Column7", "IT needs this list to drive the new regional dashboards..... Must maintain it with Carley - this is my copy."})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

