table 'Starts Budget'
	lineageTag: d41d6eb2-fd9e-4c10-bec6-e9d63936dbd6

	measure Current_Term_Budget = ```
			
			VAR CurrentYear = YEAR(TODAY())
			VAR CurrentQuarter = QUARTER(TODAY())
			VAR StartMonth = (CurrentQuarter - 1) * 3 + 1
			VAR Starts= 
			    CALCULATE(
			        SUM('Starts Budget'[Value]),
			        'Starts Budget'[Year] = CurrentYear,
			        SWITCH(
			          'Starts Budget'[Month],
			            "January", 1,
			            "February", 2,
			            "March", 3,
			            "April", 4,
			            "May", 5,
			            "June", 6,
			            "July", 7,
			            "August", 8,
			            "September", 9,
			            "October", 10,
			            "November", 11,
			            "December", 12,
			            0  -- Default value in case of an invalid month
			        ) >= StartMonth,
			        SWITCH(
			            'Starts Budget'[Month],
			            "January", 1,
			            "February", 2,
			            "March", 3,
			            "April", 4,
			            "May", 5,
			            "June", 6,
			            "July", 7,
			            "August", 8,
			            "September", 9,
			            "October", 10,
			            "November", 11,
			            "December", 12,
			            0  -- Default value in case of an invalid month
			        ) <= MONTH(TODAY())
			    )
			
			RETURN 
			IF(ISBLANK(Starts), 0, Starts)
			
			
			// VAR CurrentYear = YEAR(TODAY())
			// VAR CurrentMonth = FORMAT((TODAY()),"MMMM")
			// VAR Budget = 
			//     CALCULATE(
			//         SUM('Starts Budget'[Value]),
			//         'Starts Budget'[Year] = CurrentYear &&
			//         'Starts Budget'[Month] = CurrentMonth
			//     )
			// RETURN
			// IF(Budget = BLANK(), 0, Budget)
			
			```
		formatString: #,0
		lineageTag: 565b2e46-8343-417f-aa62-e00fe3d7c4f3

	measure CurrentTermBudget% = ```
			
			var CUrrentVar = [CurrentTerm]-[Current_Term_Budget]
			var final = DIVIDE(CUrrentVar,[Current_Term_Budget],0)
			return
			
			IF(
			        [CurrentTerm]> [Current_Term_Budget],             
			        CONCATENATE("+", FORMAT(final, "0.00%")),      
			        CONCATENATE("-", FORMAT(ABS(final), "0.00%"))   
			    )
			
			```
		lineageTag: b9c65939-d12e-4d6e-bd8a-8b055e6c55a8

	measure StartsFlag = IF([CurrentTerm] > [Current_Term_Budget], UNICHAR(9650), UNICHAR(9660))
		lineageTag: 435f8a9d-f2dd-4c10-b651-1ed9e9659c0b

	column Campus
		dataType: string
		lineageTag: 74b58eac-78c6-4990-94da-1de2cadde315
		summarizeBy: none
		sourceColumn: Campus

		annotation SummarizationSetBy = Automatic

	column Program
		dataType: string
		lineageTag: b94fb475-4958-4817-84ef-a4c6c2894ceb
		summarizeBy: none
		sourceColumn: Program

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b7f78c13-906b-4177-9fa6-2250cea86388
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 9570d814-4444-4be8-b765-d565694338c8
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: cb727c20-7143-4816-8371-eb59914173e9
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Campus_New = LOOKUPVALUE('Campus Region'[LOCATIONS_ID],'Campus Region'[LOCATIONS_ID],[Campus],"OTHER")
		lineageTag: b7453ab6-1b4d-4643-96e3-b8ea6af90b04
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'HCA Indicator'
		dataType: string
		lineageTag: 71bcbcc4-bdc5-41ef-83fa-fc3b3a7edf97
		summarizeBy: none
		sourceColumn: HCA Indicator

		annotation SummarizationSetBy = Automatic

	partition 'Starts Budget' = m
		mode: import
		queryGroup: 'New Starts'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://hcahealthcare.sharepoint.com/sites/HTPS-GalenCollaboration/Shared%20Documents/Project%20Folder/Executive%20Dashboards/Student%20Enrollment%20Budget.xlsx"), null, true),
				    #"Starts - Monthly_Sheet" = Source{[Item="Starts - Monthly",Kind="Sheet"]}[Data],
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Starts - Monthly_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"Campus", type text}, {"Program", type text}, {"HCA Indicator", type any}, {"January", Int64.Type}, {"February", type any}, {"March", type any}, {"April", Int64.Type}, {"May", type any}, {"June", type any}, {"July", Int64.Type}, {"August", type any}, {"September", type any}, {"October", Int64.Type}, {"November", type any}, {"December", type any}, {"Year", Int64.Type}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Campus", "Program", "HCA Indicator", "Year"}, "Attribute", "Value"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Month"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns1",2025,"",Replacer.ReplaceValue,{"Value"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Replaced Value1","            -","",Replacer.ReplaceValue,{"Value"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value","                  -","",Replacer.ReplaceValue,{"Value"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","              -","",Replacer.ReplaceValue,{"Value"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value3",{{"Campus", type text}, {"Program", type text}, {"HCA Indicator", type any}, {"Year", Int64.Type}, {"Month", type text}, {"Value", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

