table 'Dim Survey Headers'
	lineageTag: 2764b20a-a154-4edd-92dc-f33b38d36d4f

	column Recommend
		dataType: string
		lineageTag: 05855fde-2bf6-4782-bc34-34ddbd853167
		summarizeBy: none
		sourceColumn: Recommend

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 3a49872d-6815-49b6-b176-f1cbeba5849d
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition 'Dim Survey Headers' = m
		mode: import
		queryGroup: Surveys
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WinQNVtJRMlSK1YlW8vMHMo3AzFA/bz//cD8g3xjMD3INDvD3c3F1AYqYgEWCQ4PCXCPBAqZKsbEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Recommend = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Recommend", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

