table Ethnicity
	isHidden
	lineageTag: f6ec824b-6054-482c-bf17-fb0b2b7078db

	column STUDENT_ID
		dataType: string
		isHidden
		lineageTag: 059c7af4-c8a9-467d-a8ad-28dea66d79af
		summarizeBy: none
		sourceColumn: STUDENT_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IPEDS_RACE_ETHNIC_DESC
		dataType: string
		isHidden
		lineageTag: 93aecea0-0da6-46c5-a5c3-292de0a5aefc
		summarizeBy: none
		sourceColumn: IPEDS_RACE_ETHNIC_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Custom
		dataType: string
		isHidden
		lineageTag: c909e324-c758-4a28-968d-3ad4333c75f4
		summarizeBy: none
		sourceColumn: Custom

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Ethnicity = m
		mode: import
		queryGroup: Students
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "coll18_repl_production", [Query="SELECT DISTINCT STUDENT_ID, IPEDS_RACE_ETHNIC_DESC #(lf)FROM STUDENT_ACAD_PROGRAMS_VIEW WITH (NOLOCK);"]),
				    #"Added Custom" = Table.AddColumn(Source, "Custom", each ""),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each true)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

