table 'FACT_Construction Legend'
	lineageTag: b8ba5243-1c8a-4032-baef-de038c3842e9

	column 'Legend Type'
		dataType: string
		lineageTag: 5e2bc7ce-faf2-4266-a533-6463852ccb57
		summarizeBy: none
		sourceColumn: Legend Type

		annotation SummarizationSetBy = Automatic

	column 'Color Description'
		dataType: string
		lineageTag: 1c0890d4-094b-4745-8018-9ceb9ebd35fb
		summarizeBy: none
		sourceColumn: Color Description
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: b20ddaeb-dae6-447c-99d3-537bec239520
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: string
		lineageTag: a249b8e5-a36c-4639-bcd0-1eb651ab590f
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column Dot = SWITCH(TRUE(),[Color] = "Green",UNICHAR(128994),[Color] = "Red", UNICHAR(128308), [Color] = "Black",UNICHAR(9899), [Color] = "Yellow",UNICHAR(128993))
		lineageTag: 7bd5a0ac-a552-4f1c-8b76-56bfa337c74c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'FACT_Construction Legend' = m
		mode: import
		queryGroup: Academics
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://hcahealthcare.sharepoint.com/sites/HTPS-GalenCollaboration/Shared%20Documents/Project%20Folder/Executive%20Dashboards/Construction%20Reporting/ConstructionReporting.xlsx"), null, true),
				    Table1_Table = Source{[Item="Legend",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"Sort", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,"0",Replacer.ReplaceValue,{"Sort"})
				in
				    #"Replaced Value"

