table 'FACT_Student Load'
	lineageTag: 1b0707c8-b876-4e19-96d3-5f155cee67c5

	measure Students_Count_Fulltime = CALCULATE(count('FACT_Student Load'[STUDENT_ID]),DIM_Student_Load[Student Load]="FT")+0
		formatString: #,0
		lineageTag: ef2e4df1-c3f0-4219-81c6-396e73ce046d

	measure Students_Count_PartTime = CALCULATE(count('FACT_Student Load'[STUDENT_ID]),DIM_Student_Load[Student Load]="PT")+0
		formatString: #,0
		lineageTag: 0ae74e3e-a48f-48c3-a940-3973634cc06e

	measure Students_FT% =
			
			DIVIDE([Students_Count_Fulltime],[Student_Load_Count],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 74fe2003-3bcd-41c8-8477-4dbca248dea6

	measure Student_Load_Count = COUNT('FACT_Student Load'[STUDENT_ID])
		formatString: 0
		lineageTag: 68c7939c-9630-4ee2-bb1c-c9b585e319ee

	measure Students_PT% =
			
			DIVIDE([Students_Count_PartTime],[Student_Load_Count],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 7c38a978-9a04-4c04-b639-1063e6fd67fc

	column STUDENT_ID
		dataType: string
		lineageTag: d15cdb68-9230-4b74-8c0d-70f84f3084e7
		summarizeBy: none
		sourceColumn: STUDENT_ID

		annotation SummarizationSetBy = Automatic

	column PROGRAM_ID
		dataType: string
		lineageTag: 2c2ae7cb-e5df-4b6b-ac4b-a29a73df21cf
		summarizeBy: none
		sourceColumn: PROGRAM_ID

		annotation SummarizationSetBy = Automatic

	column MOST_RECENT_PROGRAM
		dataType: int64
		formatString: 0
		lineageTag: dbfd6dda-ea43-4ddb-8c46-8621fa528ad6
		summarizeBy: sum
		sourceColumn: MOST_RECENT_PROGRAM

		annotation SummarizationSetBy = Automatic

	column STUDENT_PROGRAMS_ID
		dataType: string
		lineageTag: 63326f5e-4891-4fa9-b2b6-149b9678a92b
		summarizeBy: none
		sourceColumn: STUDENT_PROGRAMS_ID

		annotation SummarizationSetBy = Automatic

	column STPR_LOCATION
		dataType: string
		lineageTag: 94990ffb-0b33-4f67-84db-3ad694137912
		summarizeBy: none
		sourceColumn: STPR_LOCATION

		annotation SummarizationSetBy = Automatic

	column STPR_ADMIT_STATUS
		dataType: string
		lineageTag: 1cfb7396-f50b-4ce6-b078-bf2d5b7cd8ed
		summarizeBy: none
		sourceColumn: STPR_ADMIT_STATUS

		annotation SummarizationSetBy = Automatic

	column STPR_STATUS
		dataType: string
		lineageTag: bdb822a2-fd40-4076-b342-69046020563b
		summarizeBy: none
		sourceColumn: STPR_STATUS

		annotation SummarizationSetBy = Automatic

	column STPR_STATUS_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: dbe8c600-0ca8-4162-8c53-a802b7a5f7a6
		summarizeBy: none
		sourceColumn: STPR_STATUS_DATE

		variation Variation
			isDefault
			relationship: 7c3fd6f4-f930-4111-8bc1-c275f9205a89
			defaultHierarchy: LocalDateTable_b799f5cb-726a-41ba-af7d-3e757cfa985c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STPR_START_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b10ce32-502f-458e-adb3-087ff39cd62c
		summarizeBy: none
		sourceColumn: STPR_START_DATE

		variation Variation
			isDefault
			relationship: 1d4407db-5a89-4508-b11b-16b775d58e74
			defaultHierarchy: LocalDateTable_504ef19a-6a04-44f7-91aa-90c544a8f86e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STPR_END_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: c9251162-e8d3-4609-bf88-c29736d59408
		summarizeBy: none
		sourceColumn: STPR_END_DATE

		variation Variation
			isDefault
			relationship: f0b94f36-403f-4db2-9bda-949a6318d05a
			defaultHierarchy: LocalDateTable_03bfc0b1-6c2d-4c95-afa2-52fe290c2e42.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ProgramStatus
		dataType: string
		lineageTag: 0a8684f3-da8c-43ec-b79f-950c548f82c8
		summarizeBy: none
		sourceColumn: ProgramStatus

		annotation SummarizationSetBy = Automatic

	column AdmissionStatus
		dataType: string
		lineageTag: 0b6f98c8-2fc2-4363-8c19-38c2428c9759
		summarizeBy: none
		sourceColumn: AdmissionStatus

		annotation SummarizationSetBy = Automatic

	column ACPG_ACAD_LEVEL
		dataType: string
		lineageTag: 5da87b84-ba07-4507-8f94-919ae5e59af9
		summarizeBy: none
		sourceColumn: ACPG_ACAD_LEVEL

		annotation SummarizationSetBy = Automatic

	column LOC_DESC
		dataType: string
		lineageTag: 16cdfa6c-7979-4fd5-bc2f-55b18a06ed1f
		summarizeBy: none
		sourceColumn: LOC_DESC

		annotation SummarizationSetBy = Automatic

	column FIRST_NAME
		dataType: string
		lineageTag: 3130b510-73a6-467d-80c8-0d6ca9e26703
		summarizeBy: none
		sourceColumn: FIRST_NAME

		annotation SummarizationSetBy = Automatic

	column LAST_NAME
		dataType: string
		lineageTag: 2d3b5798-5033-4de4-b330-3f824ea41189
		summarizeBy: none
		sourceColumn: LAST_NAME

		annotation SummarizationSetBy = Automatic

	column FTorPT
		dataType: string
		lineageTag: af264d5c-7115-44c4-9560-d5c8f4f2b0a1
		summarizeBy: none
		sourceColumn: FTorPT

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: e7851910-b259-4005-a60a-51c17ac677b2
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Next_STPR_STATUS_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: d45280b1-f9cd-4922-8610-52a169bdbda8
		summarizeBy: none
		sourceColumn: Next_STPR_STATUS_DATE

		variation Variation
			isDefault
			relationship: 8fb4aa5c-8a43-4302-8a42-a266ad10eac2
			defaultHierarchy: LocalDateTable_2fde889e-5516-4550-b1a4-497a4136712f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Year Sort'
		dataType: string
		lineageTag: d372a338-7fdb-4b17-8cb9-94f395de6929
		summarizeBy: none
		sourceColumn: Year Sort

		annotation SummarizationSetBy = Automatic

	partition 'FACT_Student Load' = m
		mode: import
		queryGroup: 'Student Load'
		source =
				let
				    Source = Table.Combine({#"FACT_Student Load CY", #"FACT_Student Load LY", #"FACT_Student Load 2Y"})
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

