table 'Forecasted Drops'
	lineageTag: 75261d2d-0b39-4ebd-82b1-f6ea5c80164a

	measure ForecastedDifference = ```
			
			 VAR Forecast1 = [CurrentTermDR]- [CumulativeForecastedDrops]
			
			 return
			
			//Forecast1
			     IF(
			        ('Students Dropped'[CurrentTermDR]) >[CumulativeForecastedDrops],             
			        CONCATENATE("+", FORMAT(DIVIDE(Forecast1,[CumulativeForecastedDrops],0), "0.00%")),      
			        CONCATENATE("-", FORMAT(ABS(DIVIDE(Forecast1,[CumulativeForecastedDrops],0)), "0.00%")   
			    ))
			```
		lineageTag: 6ce4d217-e2c5-4823-8e76-28023108f7e1

	measure ForecasteFlag =
			
			IF([CurrentTermDR]>[CumulativeForecastedDrops], UNICHAR(9650), UNICHAR(9660))
		lineageTag: d2812577-86e3-4036-827a-c1228ef3832e

	measure NearestStartWeek = ```
			
			    VAR TodayDate = TODAY()
			    VAR MinDiff = MINX(
			        'Forecasted Drops',
			        ABS(TodayDate - 'Forecasted Drops'[AdjustedDate])
			    )
			    RETURN
			        MINX(
			            FILTER(
			                'Forecasted Drops',
			                ABS(TodayDate - 'Forecasted Drops'[AdjustedDate]) = MinDiff
			            ),
			            'Forecasted Drops'[start_wk]
			        )
			
			```
		formatString: General Date
		lineageTag: bf760e9b-1210-47d5-aa0b-c8f80ab5836d

	measure CumulativeForecastedDrops = ```
			
			VAR StartWeekDate = [NearestStartWeek]
			VAR TodayDate = TODAY()
			VAR CurrentTermStartDate =
			    CALCULATE(
			        MAX('Dim_Terms'[term_start_date]),
			        FILTER(ALL('Dim_Terms'), 'Dim_Terms'[term_start_date] <= TodayDate)
			    )
			
			VAR NextTermStartDate =
			    CALCULATE(
			        MIN('Dim_Terms'[term_start_date]),
			        FILTER(ALL('Dim_Terms'), 'Dim_Terms'[term_start_date] > CurrentTermStartDate)
			    )
			VAR StillInCurrentTerm = ISBLANK(NextTermStartDate) || TodayDate < NextTermStartDate
			VAR FINAL =
			    IF(
			        StillInCurrentTerm,
			        CALCULATE(
			            SUM('Forecasted Drops'[n]),
			            FILTER(
			                'Forecasted Drops',
			                'Forecasted Drops'[start_wk] >= StartWeekDate &&
			                'Forecasted Drops'[AdjustedDate] <= TodayDate
			            )
			        ),
			        CALCULATE(
			            SUM('Forecasted Drops'[n]),
			            FILTER(
			                'Forecasted Drops',
			                'Forecasted Drops'[start_wk] >= NextTermStartDate &&
			                'Forecasted Drops'[AdjustedDate] <= TodayDate
			            )
			        )
			    )
			
			RETURN
			IF(ISBLANK(FINAL), 0, FINAL)
			
			
			
			
			
			
			
			    // VAR StartWeekDate = [NearestStartWeek]
			    // VAR TodayDate = TODAY()
			    // VAR FINAL = 
			    //     CALCULATE(
			    //         SUM('Forecasted Drops'[n]),
			    //         FILTER(
			    //             'Forecasted Drops',
			    //             'Forecasted Drops'[start_wk] >= StartWeekDate &&
			    //             'Forecasted Drops'[AdjustedDate] <= TodayDate
			    //         ))
			    //     RETURN
			    //     IF (FINAL = BLANK(), 0, FINAL)
			
			```
		formatString: 0
		lineageTag: 5cdbf7a5-5caf-4bfb-9bd6-65dde078f322

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ForecastedDropsFlag = IF([CurrentTermDR]>[CumulativeForecastedDrops], "#C81515", "#00B050")
		lineageTag: 531ef520-0dfa-4c8f-80e5-c6be6ba74ed2

	measure 'Test debug' = ```
			
			VAR TodayDate = TODAY()
			
			VAR PreviousTermStartDate = 
			    CALCULATE(
			        MAX('Forecasted Drops'[start_wk]),
			        FILTER(
			            ALL('Forecasted Drops'),
			            'Forecasted Drops'[start_wk] < TodayDate  -- Get the most recent term before today
			        )
			    )
			
			RETURN PreviousTermStartDate
			
			
			```
		formatString: General Date
		lineageTag: 4aa6bb91-bcc4-404a-b0b7-b9f7cf35e0c9

	column Campus
		dataType: string
		lineageTag: 8ee4b656-c0d2-45c3-bd68-af521b63df22
		summarizeBy: none
		sourceColumn: Campus

		annotation SummarizationSetBy = Automatic

	column Program
		dataType: string
		lineageTag: d4eff9df-c9c7-465b-be19-ce48cb060d60
		summarizeBy: none
		sourceColumn: Program

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: string
		lineageTag: d2b81bf9-f355-4b56-b8ae-389461328737
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

	column start_wk
		dataType: dateTime
		formatString: Mm/dd/yyyy
		lineageTag: 1127c547-3a4a-47a7-854d-e15ae3dd1ff9
		summarizeBy: none
		sourceColumn: start_wk

		variation Variation
			isDefault
			relationship: 8c00fef7-cdd1-4e9a-909b-1e951ed4cce6
			defaultHierarchy: LocalDateTable_dfddc22b-a101-4d67-adb9-2e7236946afb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column term_drop_week
		dataType: double
		lineageTag: ea323cf7-829e-4a20-ad30-e137398c4f40
		summarizeBy: sum
		sourceColumn: term_drop_week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column n
		dataType: double
		lineageTag: febc5d60-a919-4763-a09d-73a923b45493
		summarizeBy: sum
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column upper_conf
		dataType: double
		lineageTag: 139f6932-79b7-4247-8672-6e41ba26f5b4
		summarizeBy: sum
		sourceColumn: upper_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lower_conf
		dataType: double
		lineageTag: 4d4b0f0f-01de-41fe-811d-860a054f8938
		summarizeBy: sum
		sourceColumn: lower_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STC_TERM
		dataType: string
		lineageTag: ba1b5333-2b23-4c99-aca0-89ea38e41bd8
		summarizeBy: none
		sourceColumn: STC_TERM

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 9573bf19-54ff-47f1-a5ac-f38775ffe479
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column forecast_effective_week
		dataType: dateTime
		formatString: General Date
		lineageTag: 679c0e85-b97b-43c6-8c2d-bff65f23fd6f
		summarizeBy: none
		sourceColumn: forecast_effective_week

		variation Variation
			isDefault
			relationship: b30a0b68-384f-4f49-9379-e2adc0e21976
			defaultHierarchy: LocalDateTable_56e535c2-7ec8-4784-9bf5-563b4e0ddf7e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column exclude
		dataType: double
		lineageTag: 59bacadd-c170-4aac-8b0e-851e5a464199
		summarizeBy: sum
		sourceColumn: exclude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column forecast_type_code
		dataType: string
		lineageTag: a936e7cc-a877-4991-9ff4-f7fde088011a
		summarizeBy: none
		sourceColumn: forecast_type_code

		annotation SummarizationSetBy = Automatic

	column forcast_subtype_code
		dataType: string
		lineageTag: d68d3071-bc69-47bb-bce5-c2239a00a8ca
		summarizeBy: none
		sourceColumn: forcast_subtype_code

		annotation SummarizationSetBy = Automatic

	column record_written_dt
		dataType: dateTime
		formatString: General Date
		lineageTag: 9de6e6ca-9a9a-4d43-bd3e-c7fb1816296d
		summarizeBy: none
		sourceColumn: record_written_dt

		variation Variation
			isDefault
			relationship: d82291ee-dfee-478b-b622-2132304414cb
			defaultHierarchy: LocalDateTable_87e071fd-77d8-4db6-b776-3c0d97850049.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column record_source_system
		dataType: string
		lineageTag: aa9d395f-db7b-488d-8daf-19d56daca37b
		summarizeBy: none
		sourceColumn: record_source_system

		annotation SummarizationSetBy = Automatic

	column AdjustedDate = ```
			
			 'Forecasted Drops'[start_wk] + ('Forecasted Drops'[term_drop_week]*7)
			
			```
		formatString: General Date
		lineageTag: 958ff54f-7a70-4bb5-ae03-81a83e77da7e
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 0a98d38f-d261-441b-add9-b94d954897f5
			defaultHierarchy: LocalDateTable_7afbff78-60ce-49f5-81bf-584f4c1346a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column IsDateInRange = ```
			
			    VAR TodayDate = TODAY()
			    RETURN 
			        IF(
			            'Forecasted Drops'[AdjustedDate] <= TodayDate,
			            TRUE(),
			            FALSE()
			        )
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 98d99f19-1686-45bc-929c-8fd54a6f3cd8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Forecasted Drops' = m
		mode: import
		queryGroup: Drops
		source =
				let
				    Source = Sql.Database("SQL02", "GLNT-InstitutionalEffectiveness", [Query="SELECT *#(lf)  FROM [GLNT-InstitutionalEffectiveness].[dbo].[drops_arima_forecasting_ds]"])
				in
				    Source

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

