table Goals
	lineageTag: bd20d7e2-bb62-428b-ac6d-fe25e1385072

	measure GoalsFutureTerms = ```
			
			VAR TodayDate = TODAY()
			
			VAR NextRecentDate = 
			    CALCULATE(
			        MINX(
			            FILTER(
			                'Dim_Terms',
			                'Dim_Terms'[TERM_START_DATE] >= TodayDate
			            ),
			            'Dim_Terms'[TERM_START_DATE]
			        )
			    )
			
			VAR FINAL =
			CALCULATE(SUM(Goals[gcn_AdmissionsGoal]), 'DIM_Terms'[IsNextTerm] = TRUE())
			RETURN
			IF(FINAL = BLANK(),0,FINAL)
			```
		formatString: #,0
		lineageTag: deea306a-eb72-4a1d-be2b-6700a21a538f

	measure Goals% = ```
			
			VAR CUR_PRE = 'Cohorts Future Terms'[Future Terms​] - Goals[GoalsFutureTerms]
			VAR final = DIVIDE(CUR_PRE, Goals[GoalsFutureTerms],0)
			RETURN
			    IF(
			        Goals[GoalsFutureTerms] < 'Cohorts Future Terms'[Future Terms​],             
			        CONCATENATE("+", FORMAT(final, "0.00%")),      
			        CONCATENATE("-", FORMAT(ABS(final), "0.00%"))   
			    )
			```
		lineageTag: 6e514ca8-fd10-4d8a-898e-8b10dc6b649c

	measure GoalsFlag = IF(Goals[GoalsFutureTerms] < 'Cohorts Future Terms'[Future Terms​], UNICHAR(9650), UNICHAR(9660))
		lineageTag: 6c81a925-40b9-4a4f-8738-a3ce6b20b3bb

	measure GoalsColorCode = IF(Goals[GoalsFutureTerms] < 'Cohorts Future Terms'[Future Terms​], "#00B050",  "#C81515")
		lineageTag: ab023056-83b9-4cd2-acc7-f759807145f1

	column gcn_StartTerm
		dataType: string
		lineageTag: 55b359a2-f84b-4d0f-8c2e-1b2490517505
		summarizeBy: none
		sourceColumn: gcn_StartTerm

		annotation SummarizationSetBy = Automatic

	column gcn_Location
		dataType: string
		lineageTag: 50981ab3-39b7-4b3f-96c3-56bcfeea9c06
		summarizeBy: none
		sourceColumn: gcn_Location

		annotation SummarizationSetBy = Automatic

	column gcn_AcademicProgram
		dataType: string
		lineageTag: 7e64320f-11fe-4209-8057-b79cff4fec25
		summarizeBy: none
		sourceColumn: gcn_AcademicProgram

		annotation SummarizationSetBy = Automatic

	column gcn_AdmissionsGoal
		dataType: int64
		formatString: 0
		lineageTag: 11b7dbc4-41c8-4b3f-b30d-904c3373b055
		summarizeBy: sum
		sourceColumn: gcn_AdmissionsGoal

		annotation SummarizationSetBy = Automatic

	partition Goals = m
		mode: import
		queryGroup: Students
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "GalenCollegeCRM_MSCRM", [Query="SELECT * fROM gcn_galenadmissionsgoalBase"]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"gcn_galenadmissionsgoalId", "CreatedOn", "CreatedBy", "ModifiedOn", "ModifiedBy", "CreatedOnBehalfBy", "ModifiedOnBehalfBy", "OwnerId", "OwnerIdType", "OwningBusinessUnit", "statecode", "statuscode", "VersionNumber", "ImportSequenceNumber", "OverriddenCreatedOn", "TimeZoneRuleVersionNumber", "UTCConversionTimeZoneCode", "gcn_name"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

