table 'Load Sort'
	lineageTag: 30392ce1-1ef9-49ea-9668-f92c4a53935d

	column Load
		dataType: string
		lineageTag: aaffa892-6005-430e-8657-743a57da02e3
		summarizeBy: none
		sourceColumn: Load
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 586ee879-b35c-4ae0-ba5f-fcc7f6778f4b
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column Load2
		dataType: string
		lineageTag: 709bfcd8-696f-4c2a-988e-7d86b82af5e2
		summarizeBy: none
		sourceColumn: Load2
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition 'Load Sort' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WUlbIT1NwS0wuzSmpVPBNTS3JzEtX8MlPTFHSUTIEYrcQ7LKxOmh6/ctSi3Ig+oxQ9cFlMPSE5qXANRmjakJI4dal8KhzqYKRQmBJUTFQswkOA5BVYTErsbg4Mz0vFeQEU3QT4HKxsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Load = _t, Sort = _t, Load2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Load", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

