table 'NCLEX Board Numbers'
	lineageTag: 09d1a9c4-4a3e-486c-9e48-fbf0b7ab99dc

	measure 'Total Testers - Last Quarter' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			CALCULATE(
			    SUM('NCLEX Board Numbers'[Testers]),
			    'NCLEX Board Numbers'[Year] = LastQuarterYear,
			    'NCLEX Board Numbers'[Quarter] = LastQuarterLabel
			)
			
			```
		formatString: 0
		lineageTag: acf1b4b0-c935-47b6-8b37-a6266433991d

	measure 'Total Pass Count - Last Quarter' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			CALCULATE(
			    SUM('NCLEX Board Numbers'[Pass Count]),
			    'NCLEX Board Numbers'[Year] = LastQuarterYear,
			    'NCLEX Board Numbers'[Quarter] = LastQuarterLabel
			)
			
			```
		formatString: 0
		lineageTag: a61e8399-5b30-4a5c-829a-e980bf5d1fe9

	measure 'Total Pass Count - Last Quarter (National)' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			CALCULATE(
			    SUM('NCLEX Board Numbers'[Pass Count]),
			    'NCLEX Board Numbers'[Year] = LastQuarterYear,
			    'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			    'NCLEX Board Numbers'[Campus] = "National"
			)
			
			```
		formatString: 0
		lineageTag: 3fe855c8-461b-496d-a5bb-69610de8675d

	measure 'Total Testers - Last Quarter (National, RN)' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Testers]),
			        'NCLEX Board Numbers'[Year] = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus] = "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "RN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 71335239-a51a-41f6-b841-c9b93f95b62b

	measure 'Total Testers - Last Quarter (National, PN)' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Testers]),
			        'NCLEX Board Numbers'[Year] = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus] = "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "PN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 42e227f9-3d53-4035-ad6d-fc6e9d9f7067

	measure 'Total Testers - Last Quarter (Non-National, RN)' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Testers]),
			        'NCLEX Board Numbers'[Year] = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus] <> "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "RN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: d5e9c3a9-ac9a-4269-afa3-750da018c915

	measure 'Total Testers - Last Quarter (Non-National, PN)' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Testers]),
			        'NCLEX Board Numbers'[Year] = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus] <> "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "PN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: cb8ac507-0ea8-469d-a2a5-b901a8e74767

	measure 'Total Pass Count - Last Quarter (Non-National, RN)' = ```
			
			VAR CurrentDate          = TODAY()
			VAR CurrentYear          = YEAR(CurrentDate)
			VAR CurrentMonth         = MONTH(CurrentDate)
			VAR CurrentQuarterNumber =
			    SWITCH ( TRUE(),
			        CurrentMonth IN { 1, 2, 3 }, 1,
			        CurrentMonth IN { 4, 5, 6 }, 2,
			        CurrentMonth IN { 7, 8, 9 }, 3,
			        4
			    )
			VAR LastQuarterNumber    = IF ( CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1 )
			VAR LastQuarterYear      = IF ( CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear )
			VAR LastQuarterLabel     = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE (
			        SUM ( 'NCLEX Board Numbers'[Pass Count] ),
			        'NCLEX Board Numbers'[Year]    = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus]  <> "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "RN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 7f79c199-c222-48e9-a1a1-9d91a844dcb8

	measure 'Total Pass Count - Last Quarter (Non-National, PN)' = ```
			
			VAR CurrentDate          = TODAY()
			VAR CurrentYear          = YEAR(CurrentDate)
			VAR CurrentMonth         = MONTH(CurrentDate)
			VAR CurrentQuarterNumber =
			    SWITCH ( TRUE(),
			        CurrentMonth IN { 1, 2, 3 }, 1,
			        CurrentMonth IN { 4, 5, 6 }, 2,
			        CurrentMonth IN { 7, 8, 9 }, 3,
			        4
			    )
			VAR LastQuarterNumber    = IF ( CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1 )
			VAR LastQuarterYear      = IF ( CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear )
			VAR LastQuarterLabel     = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE (
			        SUM ( 'NCLEX Board Numbers'[Pass Count] ),
			        'NCLEX Board Numbers'[Year]    = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus]  <> "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "PN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 862ea9b0-6498-4765-a1ce-acdef558c728

	measure 'Total Pass Count - Last Quarter (National, RN)' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Pass Count]),
			        'NCLEX Board Numbers'[Year] = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus] = "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "RN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 4989a078-7f3f-4628-a227-642d71261855

	measure 'Total Pass Count - Last Quarter (National, PN)' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR CurrentMonth = MONTH(CurrentDate)
			VAR CurrentQuarterNumber = 
			    SWITCH(TRUE(),
			        CurrentMonth IN {1,2,3}, 1,
			        CurrentMonth IN {4,5,6}, 2,
			        CurrentMonth IN {7,8,9}, 3,
			        4
			    )
			VAR LastQuarterNumber = IF(CurrentQuarterNumber = 1, 4, CurrentQuarterNumber - 1)
			VAR LastQuarterYear = IF(CurrentQuarterNumber = 1, CurrentYear - 1, CurrentYear)
			VAR LastQuarterLabel = "Q" & LastQuarterNumber
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Pass Count]),
			        'NCLEX Board Numbers'[Year] = LastQuarterYear,
			        'NCLEX Board Numbers'[Quarter] = LastQuarterLabel,
			        'NCLEX Board Numbers'[Campus] = "National",
			        'NCLEX Board Numbers'[NCLEX Type] = "PN"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 4d4ff8fa-e09f-4b15-83db-5adead824392

	measure 'National Pass Rates RN' = ```
			
			DIVIDE(
			    CALCULATE(
			        COALESCE([Total Pass Count - Last Quarter (National, RN)], 0),
			        REMOVEFILTERS('Campus Region'[LOC_DESC]),
			        REMOVEFILTERS('Campus Region'[LOCR_DESC])
			    ),
			    CALCULATE(
			        COALESCE([Total Testers - Last Quarter (National, RN)], 0),
			        REMOVEFILTERS('Campus Region'[LOC_DESC]),
			        REMOVEFILTERS('Campus Region'[LOCR_DESC])
			    ),
			    0
			)
			
			
			// DIVIDE(
			//     COALESCE([Total Pass Count - Last Quarter (National, RN)], 0),
			//     COALESCE([Total Testers - Last Quarter (National, RN)], 0),
			//     0
			// )
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d49aea78-0da4-4625-a47f-33692c8df033

	measure 'National Pass Rates PN' = ```
			
			DIVIDE(
			    CALCULATE(
			        COALESCE([Total Pass Count - Last Quarter (National, PN)], 0),
			        REMOVEFILTERS('Campus Region'[LOC_DESC]),
			        REMOVEFILTERS('Campus Region'[LOCR_DESC])
			    ),
			    CALCULATE(
			        COALESCE([Total Testers - Last Quarter (National, PN)], 0),
			        REMOVEFILTERS('Campus Region'[LOC_DESC]),
			        REMOVEFILTERS('Campus Region'[LOCR_DESC])
			    ),
			    0
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d8d46eea-b77f-48fa-84c7-37a5482d45d5

	measure 'NCLEX Pass Rate PN Last Qtr' = ```
			
			DIVIDE(
			    COALESCE([Total Pass Count - Last Quarter (Non-National, PN)], 0),
			    COALESCE([Total Testers - Last Quarter (Non-National, PN)], 0),
			    0
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8c61465b-2ae4-410c-93ba-99e62e2c1370

	measure 'NCLEX Pass Rate RN Last Qtr' = ```
			
			DIVIDE(
			    COALESCE([Total Pass Count - Last Quarter (Non-National, RN)], 0),
			    COALESCE([Total Testers - Last Quarter (Non-National, RN)], 0),
			    0
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1e381cf6-6b9b-4d76-94e2-2c5ef143de75

	measure 'Total Pass Count - Last Year RN' = ```
			
			VAR CurrentDate  = TODAY()
			VAR CurrentYear  = YEAR(CurrentDate)
			VAR TargetYear   = CurrentYear - 1     -- full last year
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Pass Count]),
			        'NCLEX Board Numbers'[Year] = TargetYear,
			        'NCLEX Board Numbers'[NCLEX Type] = "RN",
			        'NCLEX Board Numbers'[Campus] <> "National"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 75935427-47d1-4437-887b-bf338a2a3802

	measure 'Total Pass Count - Last Year PN' = ```
			
			VAR CurrentDate  = TODAY()
			VAR CurrentYear  = YEAR(CurrentDate)
			VAR TargetYear   = CurrentYear - 1     -- entire prior calendar year
			RETURN
			COALESCE(
			    CALCULATE (
			        SUM ( 'NCLEX Board Numbers'[Pass Count] ),
			        'NCLEX Board Numbers'[Year]        = TargetYear,
			        'NCLEX Board Numbers'[NCLEX Type]  = "PN",
			        'NCLEX Board Numbers'[Campus]     <> "National"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: e1dabfd4-c533-4981-a99c-d437b07701ba

	measure 'Total Testers - Last Year RN' = ```
			
			VAR CurrentDate  = TODAY()
			VAR CurrentYear  = YEAR(CurrentDate)
			VAR TargetYear   = CurrentYear - 1    
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Testers]),
			        'NCLEX Board Numbers'[Year] = TargetYear,
			        'NCLEX Board Numbers'[NCLEX Type] = "RN",
			        'NCLEX Board Numbers'[Campus] <> "National"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: a0adc083-9083-471e-a4fe-2bfb95b31b57

	measure 'Total Testers - Last Year PN' = ```
			
			VAR CurrentDate = TODAY()
			VAR CurrentYear = YEAR(CurrentDate)
			VAR TargetYear = CurrentYear - 1
			RETURN
			COALESCE(
			    CALCULATE(
			        SUM('NCLEX Board Numbers'[Testers]),
			        'NCLEX Board Numbers'[Year] = TargetYear,
			        'NCLEX Board Numbers'[NCLEX Type] = "PN",
			        'NCLEX Board Numbers'[Campus] <> "National"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: a8ea62ab-ac31-40ad-9d9e-09bed2e06733

	measure 'NCLEX Pass Rate PN Last Year' = ```
			
			DIVIDE(
			    COALESCE([Total Pass Count - Last Year PN], 0),
			    COALESCE([Total Testers - Last Year PN], 0),
			    0
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6189be0b-1d6a-40d0-8289-ceac0325373c

	measure 'NCLEX Pass Rate RN Last Year' = ```
			
			DIVIDE(
			    COALESCE([Total Pass Count - Last Year RN], 0),
			    COALESCE([Total Testers - Last Year RN], 0),
			    0
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d6df07ce-bfd7-4f58-a1a5-72af486f5db8

	measure PNColor2 = ```
			
			IF(
			    [NCLEX Pass Rate PN Last Qtr] < [NCLEX Pass Rate PN Last Year] 
			    || [NCLEX Pass Rate PN Last Qtr] < [National Pass Rates PN], 
			    "#C00000", 
			    "#000000"
			)
			```
		lineageTag: 2c950307-2156-4ba5-8d3c-e30c749caf5d

	measure RNColor2 = ```
			
			IF([NCLEX Pass Rate RN Last Qtr] < [NCLEX Pass Rate RN Last Year]
				|| [NCLEX Pass Rate PN Last Qtr] < [National Pass Rates RN],
				"#C00000", 
				"#000000")
			```
		lineageTag: 9deb5881-8ccb-45a1-ae18-e6d33c3c7b3d

	column Campus
		dataType: string
		lineageTag: a02f55a9-bbda-41bf-a092-dc359be8bdda
		summarizeBy: none
		sourceColumn: Campus

		annotation SummarizationSetBy = Automatic

	column 'NCLEX Type'
		dataType: string
		lineageTag: 14cbff3a-e8fa-496c-8dd4-d790d6fbdf5b
		summarizeBy: none
		sourceColumn: NCLEX Type

		annotation SummarizationSetBy = Automatic

	column Program
		dataType: string
		lineageTag: d6ee20aa-a064-48b7-a3df-e628e85e6a74
		summarizeBy: none
		sourceColumn: Program

		annotation SummarizationSetBy = Automatic

	column Testers
		dataType: int64
		formatString: 0
		lineageTag: afc2741b-88b1-496d-bb03-50c2d4b60c10
		summarizeBy: sum
		sourceColumn: Testers

		annotation SummarizationSetBy = Automatic

	column 'Pass Count'
		dataType: int64
		formatString: 0
		lineageTag: d861fdcd-19a2-4bb8-bf7f-8400b8be0e53
		summarizeBy: sum
		sourceColumn: Pass Count

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: a522cfee-6c56-4cd5-80bd-f8267ee6a502
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5943361f-e705-4cab-bcda-d643f7bb9de1
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Validity
		dataType: int64
		formatString: 0
		lineageTag: 1bbca268-b4cb-4360-be07-5fc213c8897c
		summarizeBy: sum
		sourceColumn: Validity

		annotation SummarizationSetBy = Automatic

	column 'Date Updated'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cd9eef09-e5ab-479a-bdd0-fe824ca48945
		summarizeBy: none
		sourceColumn: Date Updated

		variation Variation
			isDefault
			relationship: 37397ca1-2391-4b16-abcd-d6f21c6b66c5
			defaultHierarchy: LocalDateTable_6d40b98f-e95c-4bb9-8192-9039d21de2eb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'NCLEX Board Numbers' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://hcahealthcare.sharepoint.com/sites/HTPS-GalenCollaboration/Shared%20Documents/Project%20Folder/Executive%20Dashboards/NCLEX%20Board%20Numbers.xlsx"), null, true),
				    #"NCLEX Board Numbers_Sheet" = Source{[Item="NCLEX Board Numbers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"NCLEX Board Numbers_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Campus", type text}, {"NCLEX Type", type text}, {"Program", type text}, {"Testers", Int64.Type}, {"Pass Count", Int64.Type}, {"Quarter", type text}, {"Year", Int64.Type}, {"Validity", Int64.Type}, {"Date Updated", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

