table 'Students Dropped'
	lineageTag: 8e970aaf-2525-4977-9262-d9d9c84fdeb3

	measure CurrentTermDR =
			
			var maxpastdate = MAXX(FILTER('DIM_Terms' ,'DIM_Terms'[TERM_START_DATE]<=TODAY()),'DIM_Terms'[TERM_START_DATE])
			
			VAR FINAL = CALCULATE(count('Students Dropped'[STUDENT_PROGRAMS_ID]),DIM_Terms[TermDuringBreak] = "True")
			RETURN
			IF(FINAL=BLANK(),0,FINAL)
		formatString: #,0
		lineageTag: 7d56db2b-6763-4fb4-a6e2-80341bf0c0de

	measure Withdrawals_Count = ```
			
			CALCULATE(count('Students Dropped'[STUDENT_PROGRAMS_ID]),DIM_Terms[TermDuringBreak]="True",'Students Dropped'[HIATUS_CODE]="Withdrawal")+0
			
			```
		formatString: #,0
		lineageTag: 10095671-1817-4181-83df-1af96b3ed3bb

	measure Dismissals_Count =
			
			// var maxpastdate = MAXX(FILTER('DIM_Terms' ,'DIM_Terms'[TERM_START_DATE]<=TODAY()),'DIM_Terms'[TERM_START_DATE])
			// return
			CALCULATE(count('Students Dropped'[STUDENT_PROGRAMS_ID]),DIM_Terms[TermDuringBreak]="True",
			'Students Dropped'[HIATUS_CODE]="Dismissed")+0
		formatString: #,0
		lineageTag: 5000504a-7ba3-4358-b5bb-45f8080e7f04

	measure PreviousYearWithdrawal =
			
			// VAR CurrentMonth = MONTH(TODAY())
			// VAR CurrentDay = DAY(TODAY())
			// VAR PreviousYearStartDate = DATE(YEAR(TODAY()) -1, CurrentMonth, CurrentDay)
			// VAR PreviousYearEndDate = DATE(YEAR(TODAY()) -1, CurrentMonth, CurrentDay)
			
			// RETURN
			
			CALCULATE(count('Students Dropped'[STUDENT_PROGRAMS_ID]),
			DIM_Terms[TermDuringBreak_LastYear] = "True",
			'Students Dropped'[HIATUS_CODE]  = "Withdrawal"
			)+0
		formatString: #,0
		lineageTag: 8179dbd8-00ca-40c1-87c1-19d80f6658b1

	measure PreviousYearDismissals = ```
			
			// VAR CurrentMonth = MONTH(TODAY())
			// VAR CurrentDay = DAY(TODAY())
			// VAR PreviousYearStartDate = DATE(YEAR(TODAY()) -1, CurrentMonth, CurrentDay)
			// VAR PreviousYearEndDate = DATE(YEAR(TODAY()) -1, CurrentMonth, CurrentDay)
			
			// RETURN
			
			CALCULATE(count('Students Dropped'[STUDENT_PROGRAMS_ID]),
			DIM_Terms[TermDuringBreak_LastYear] = "True", 
			'Students Dropped'[HIATUS_CODE]  = "Dismissed"
			)+0
			```
		formatString: #,0
		lineageTag: 40b3e90b-5d7e-4e78-8165-0841cef2834f

	measure WithdrawalFlag = IF([Withdrawals_Count]>[PreviousYearWithdrawal], UNICHAR(9650), UNICHAR(9660))
		lineageTag: 7fa01bbc-8f93-4ac7-af3e-644c79daf5f5

	measure DismissalsFlag = IF([Dismissals_Count]>[PreviousYearDismissals], UNICHAR(9650), UNICHAR(9660))
		lineageTag: 7a708556-0673-4edb-8bcb-dbca72abb43e

	measure WithdrawalColorCode = IF([Withdrawals_Count]>[PreviousYearWithdrawal], "#C81515", "#00B050")
		lineageTag: 378b7521-1dd4-42eb-b12a-d681d2430a67

	measure DismissalsColorCode = IF([Dismissals_Count]>[PreviousYearDismissals], "#C81515", "#00B050")
		lineageTag: fe83db60-14d5-44b8-82ee-6340715aa175

	measure Withdrawals_Combined = ```
			
			VAR WithdrawalsCount =
			    CALCULATE(
			        COUNT('Students Dropped'[STUDENT_PROGRAMS_ID]),
			        DIM_Terms[TermDuringBreak] = "True",
			        'Students Dropped'[HIATUS_CODE] = "Withdrawal"
			    ) + 0
			VAR TotalCount = 
			    COUNTROWS('Students Dropped') 
			VAR WithdrawalsPercentage =
			    DIVIDE(WithdrawalsCount, TotalCount, 0)
			RETURN
			    FORMAT(WithdrawalsCount, "0") & 
			    " (" & FORMAT([Withdrawals%], "0.00%") & ")"
			```
		lineageTag: a8a19e23-05f3-4a61-b6c0-3c6a5827dcdc

	measure Dismissals_Combined = ```
			
			VAR DismissalsCount =
			    CALCULATE(
			        COUNT('Students Dropped'[STUDENT_PROGRAMS_ID]),
			        DIM_Terms[TermDuringBreak] = "True",
			        'Students Dropped'[HIATUS_CODE] = "Dismissed"
			    ) + 0
			VAR TotalCount = 
			    COUNTROWS('Students Dropped') -- Replace with your total count logic
			VAR DismissalsPercentage =
			    DIVIDE(DismissalsCount, TotalCount, 0)
			RETURN
			    FORMAT(DismissalsCount, "0") & 
			    " (" & FORMAT([Dismissals%], "0.00%") & ")"
			```
		lineageTag: 216c2cda-5817-4a47-b41e-00ba4b52f9a0

	measure PreviousYearDrops1 =
			
			// VAR CurrentMonth = MONTH(TODAY())
			// VAR CurrentDay = DAY(TODAY())
			// VAR PreviousYearStartDate = DATE(YEAR(TODAY()) -1, CurrentMonth, CurrentDay)
			// VAR PreviousYearEndDate = DATE(YEAR(TODAY()) -1, CurrentMonth, CurrentDay)
			// RETURN
			CALCULATE(count('Students Dropped'[STUDENT_PROGRAMS_ID]),
			DIM_Terms[TermDuringBreak_LastYear] = "True"
			---'Students Dropped'[HIATUS_CODE]  = "Withdrawal"
			)+0
		formatString: 0
		lineageTag: b26492da-bd1b-4338-9eeb-85f464b2b97e

	measure Drops_Count1 =
			
			CALCULATE(count('Students Dropped'[STUDENT_PROGRAMS_ID]),
			DIM_Terms[TermDuringBreak]="True"
			---'Students Dropped'[HIATUS_CODE]="Withdrawal"
			)+0
		formatString: 0
		lineageTag: f08df05f-aacd-411d-a9df-b08ac60a78af

	measure DropsColorCode1 = IF([Drops_Count1]>[PreviousYearDrops1], "#C81515", "#00B050")
		lineageTag: ec7ccae6-a34a-464f-98ac-5c76bd4f42be

	column STUDENT_PROGRAMS_ID
		dataType: string
		lineageTag: 3a7c1d3a-5322-4f99-968f-96fc71763bfe
		summarizeBy: none
		sourceColumn: STUDENT_PROGRAMS_ID

		annotation SummarizationSetBy = Automatic

	column STPR_STATUS_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 319fbaed-8d6f-46c3-9384-b7cae337fa63
		summarizeBy: none
		sourceColumn: STPR_STATUS_DATE

		variation Variation
			isDefault
			relationship: 54a1337c-aa44-4329-ba20-53e9870d5c03
			defaultHierarchy: LocalDateTable_09546d8b-5b8e-43cf-822f-504ca4625c76.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STPR_STATUS
		dataType: string
		lineageTag: 3c65ef9f-5b3c-47f9-9baa-035e4c727d04
		summarizeBy: none
		sourceColumn: STPR_STATUS

		annotation SummarizationSetBy = Automatic

	column ENROLLMENT_STATUS
		dataType: string
		lineageTag: cb7150e7-39d6-4db6-a731-aad63a9402f6
		summarizeBy: none
		sourceColumn: ENROLLMENT_STATUS

		annotation SummarizationSetBy = Automatic

	column STH_REASON
		dataType: string
		lineageTag: 8b1b3e45-389b-4f54-82e7-4cab33077ab9
		summarizeBy: none
		sourceColumn: STH_REASON

		annotation SummarizationSetBy = Automatic

	column HIATUS_REASON
		dataType: string
		lineageTag: 7469fe21-4e8d-471d-91d7-8fb3009a30e7
		summarizeBy: none
		sourceColumn: HIATUS_REASON

		annotation SummarizationSetBy = Automatic

	column STH_CODE
		dataType: string
		lineageTag: 006922df-5cf9-41b6-9622-829b29484f7b
		summarizeBy: none
		sourceColumn: STH_CODE

		annotation SummarizationSetBy = Automatic

	column HIATUS_CODE
		dataType: string
		lineageTag: 365b79e9-5ec3-4d16-ab47-ffea84b49684
		summarizeBy: none
		sourceColumn: HIATUS_CODE

		annotation SummarizationSetBy = Automatic

	column STUDENT_HIATUS_ID
		dataType: string
		lineageTag: f82b3878-da43-4206-b38a-ee6103fa4da3
		summarizeBy: none
		sourceColumn: STUDENT_HIATUS_ID

		annotation SummarizationSetBy = Automatic

	column STH_STUDENT
		dataType: string
		lineageTag: 1a795158-2e3c-40ef-bba4-e22ab89acdeb
		summarizeBy: none
		sourceColumn: STH_STUDENT

		annotation SummarizationSetBy = Automatic

	column STH_START_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: d60b4e32-7669-4d87-92af-a12b9beb04a7
		summarizeBy: none
		sourceColumn: STH_START_DATE

		variation Variation
			isDefault
			relationship: 65dabd22-0130-4449-8f3e-49f90a1af10a
			defaultHierarchy: LocalDateTable_1645611b-df88-4e75-b089-39daaab91421.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STH_END_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 11c681af-50b9-434e-9b14-d497c57835b6
		summarizeBy: none
		sourceColumn: STH_END_DATE

		variation Variation
			isDefault
			relationship: 8477dd52-d6d2-4e90-a36a-9a3c65416102
			defaultHierarchy: LocalDateTable_a9fcd904-2f44-471d-87aa-e5651a6c7b0e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STH_LAST_ATTEND_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 8ab452ae-ae25-4ded-aea5-c30ab74a127d
		summarizeBy: none
		sourceColumn: STH_LAST_ATTEND_DATE

		variation Variation
			isDefault
			relationship: c114832a-daaf-4234-915e-53aff77c3dd5
			defaultHierarchy: LocalDateTable_790afc4b-dd95-4180-a9e7-a4002cfb4ac7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STH_REASON2
		dataType: string
		lineageTag: c4517b70-069f-4a97-bdc4-2e569559fd2e
		summarizeBy: none
		sourceColumn: STH_REASON2

		annotation SummarizationSetBy = Automatic

	column STH_CODE2
		dataType: string
		lineageTag: 64f57cc4-a32c-4b10-b7e3-c2209c2ddc3d
		summarizeBy: none
		sourceColumn: STH_CODE2

		annotation SummarizationSetBy = Automatic

	column STH_STATUS
		dataType: string
		lineageTag: 57dea5a6-8a1d-4733-ac0c-8909309198d7
		summarizeBy: none
		sourceColumn: STH_STATUS

		annotation SummarizationSetBy = Automatic

	column STH_TERM
		dataType: string
		lineageTag: a9daf298-5ecd-4695-9e64-1163811ae7e5
		summarizeBy: none
		sourceColumn: STH_TERM

		annotation SummarizationSetBy = Automatic

	column STUDENT_HIATUS_ADDOPR
		dataType: string
		lineageTag: befbe13b-2233-480a-a23b-3add2d86ceae
		summarizeBy: none
		sourceColumn: STUDENT_HIATUS_ADDOPR

		annotation SummarizationSetBy = Automatic

	column STUDENT_HIATUS_ADDDATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 2e33f3a9-f6ea-4ac4-964e-f4b7b266e49b
		summarizeBy: none
		sourceColumn: STUDENT_HIATUS_ADDDATE

		variation Variation
			isDefault
			relationship: 128d3dcd-43ac-4eb5-ba1c-a957f120b2fc
			defaultHierarchy: LocalDateTable_eb4fc544-83b7-4da3-9119-261d5c6d52bd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STUDENT_HIATUS_CHGOPR
		dataType: string
		lineageTag: 087fac78-e568-4de2-8706-994a8df33a2a
		summarizeBy: none
		sourceColumn: STUDENT_HIATUS_CHGOPR

		annotation SummarizationSetBy = Automatic

	column STUDENT_HIATUS_CHGDATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 2a0d30d7-9b47-4b60-883e-6bb83f2c3d1b
		summarizeBy: none
		sourceColumn: STUDENT_HIATUS_CHGDATE

		variation Variation
			isDefault
			relationship: f6c0c066-8b95-45f1-a7fc-f1755543e950
			defaultHierarchy: LocalDateTable_443853d7-a419-432b-b88f-23a6627801c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column STPR_LOCATION
		dataType: string
		lineageTag: 50b0ee07-0658-41e4-8a42-ee6a89398733
		summarizeBy: none
		sourceColumn: STPR_LOCATION

		annotation SummarizationSetBy = Automatic

	column PROGRAM_ID
		dataType: string
		lineageTag: 1b63bba8-1c90-48fb-a8e4-ef60fab70675
		summarizeBy: none
		sourceColumn: PROGRAM_ID

		annotation SummarizationSetBy = Automatic

	partition 'Students Dropped' = m
		mode: import
		queryGroup: Drops
		source =
				let
				    Source = Sql.Database("rpt2-prod.ec.galencollege.edu", "coll18_repl_production", [Query="SELECT RIGHT(SP.STUDENT_PROGRAMS_ID, LEN(SP.STUDENT_PROGRAMS_ID) - 8) PROGRAM_ID#(lf),SP.STUDENT_PROGRAMS_ID, SP.STPR_LOCATION ,STPRS.STPR_STATUS_DATE, STPRS.STPR_STATUS,  V.VAL_EXTERNAL_REPRESENTATION ENROLLMENT_STATUS,#(lf)SH.STH_REASON, WR.WDR_DESC HIATUS_REASON, SH.STH_CODE, HC.HIATUS_DESC HIATUS_CODE#(lf),SH.* #(lf)FROM STUDENT_PROGRAMS SP#(lf)INNER JOIN STPR_STATUSES STPRS ON SP.STUDENT_PROGRAMS_ID = STPRS.STUDENT_PROGRAMS_ID#(lf)INNER JOIN VALS V ON STPRS.STPR_STATUS = V.VAL_INTERNAL_CODE AND V.VALCODE_ID = 'STUDENT.PROGRAM.STATUSES'#(lf)INNER JOIN STUDENT_HIATUS SH ON LEFT(SP.STUDENT_PROGRAMS_ID, 7) = SH.STH_STUDENT AND STPRS.STPR_STATUS_DATE = SH.STH_START_DATE#(lf)INNER JOIN WITHDRAW_REASONS WR ON SH.STH_REASON = WR.WITHDRAW_REASONS_ID#(lf)INNER JOIN HIATUS_CODES HC ON SH.STH_CODE = HC.HIATUS_CODES_ID#(lf)WHERE STPRS.STPR_STATUS = 'W'#(lf)AND SH.STH_CODE <> 'CAN'#(lf)"]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"STH_USER1", "STH_USER2", "STH_USER3", "STH_USER4", "STH_USER5", "STH_USER6", "STH_USER7", "STH_USER8", "STH_USER9", "STH_USER10", "STH_INSTITUTION", "STH_APPROVAL1", "STH_APPROVAL2", "STH_APPROVAL3", "STH_EXPECTED_RETURN_DATE", "STH_MEAL_PLANS_DATE", "STH_ROOM_ASSIGNMENT_DATE", "STH_CAMPUS_ORGS_DATE", "STH_COMMUNICATION_CODE", "STH_COMMENTS", "STH_REG_DATE", "STH_WAIT_LIST_DATE"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

