table Summarize
	lineageTag: c99a5026-5e1d-4579-ab8e-4eaab3994dbc

	measure FontColor_SpecificRows = ```
			
			VAR ThisDescription = SELECTEDVALUE('Load Sort'[Load])
			VAR ThisQuarter = SELECTEDVALUE('dim_terms'[QuarterFaculty])
			VAR HighlightDescriptions = {
			    "# of Faculty Overload",
			    "# of Faculty Underload",
			    "# of Faculty Underload ≥ 2 Qtrs",
			    "# of Faculty Unassigned"
			}
			RETURN
			IF (
			    ThisDescription IN HighlightDescriptions &&
			    ThisQuarter = "Q2 2025",
			    "#C00000", 
			    BLANK()     
			)
			
			```
		lineageTag: 53a1d5c2-8dde-4dbf-a5ae-0d2ed018793d

	measure FontColor_FacultyLoad1 = ```
			
			VAR ThisDescription = SELECTEDVALUE('Load Sort'[Load])
			VAR ThisQuarter = SELECTEDVALUE('dim_terms'[QuarterFaculty])
			
			VAR HighlightDescriptions = {
			    "# of Faculty Overload",
			    "# of Faculty Underload",
			    "# of Faculty Underload ≥ 2 Qtrs",
			    "# of Faculty Unassigned"
			}
			
			-- Current value (Q2 2025)
			VAR CurrentValue =
			    CALCULATE (
			        COUNTROWS('Summarize'),
			        FILTER (
			            ALL('dim_terms'),
			            'dim_terms'[QuarterFaculty] = "Q2 2025"
			        ),
			        'Summarize'[Load Category] = ThisDescription
			    )
			
			-- Prior value (Q1 2025)
			VAR PriorValue =
			    CALCULATE (
			        COUNTROWS('Summarize'),
			        FILTER (
			            ALL('dim_terms'),
			            'dim_terms'[QuarterFaculty] = "Q1 2025"
			        ),
			        'Summarize'[Load Category] = ThisDescription
			    )
			
			RETURN
			IF (
			    ThisDescription IN HighlightDescriptions &&
			    ThisQuarter = "Q2 2025",
			    SWITCH (
			        TRUE(),
			        CurrentValue = 0, "#00B050",            -- Green
			        CurrentValue < PriorValue, "#000000",   -- Black
			        CurrentValue >= PriorValue, "#C00000",  -- Red
			        BLANK()
			    ),
			    BLANK()
			)
			
			```
		lineageTag: 719281f7-5893-4f60-a76d-72c815737b9e

	column DateRank
		formatString: 0
		lineageTag: c25dc646-b776-412e-812a-5abc24e4b356
		summarizeBy: sum
		isNameInferred
		sourceColumn: [DateRank]

		annotation SummarizationSetBy = Automatic

	column Colleague_ID
		lineageTag: 2a84bacf-a757-4525-9481-a439b981a639
		summarizeBy: none
		isNameInferred
		sourceColumn: [Colleague_ID]

		annotation SummarizationSetBy = Automatic

	column Course
		lineageTag: 611aac8d-9c4f-431e-a3af-05ac40df2e3b
		summarizeBy: none
		isNameInferred
		sourceColumn: [Course]

		annotation SummarizationSetBy = Automatic

	column EMP_STATUS
		lineageTag: b971e677-1974-4707-b528-b340c6f2943c
		summarizeBy: none
		isNameInferred
		sourceColumn: [EMP_STATUS]

		annotation SummarizationSetBy = Automatic

	column FIRST_NAME
		lineageTag: a8445256-ec2c-4a1a-8223-e4141dafdd00
		summarizeBy: none
		isNameInferred
		sourceColumn: [FIRST_NAME]

		annotation SummarizationSetBy = Automatic

	column LAST_NAME
		lineageTag: ec1cf070-9683-4a30-b3a0-6e545777145b
		summarizeBy: none
		isNameInferred
		sourceColumn: [LAST_NAME]

		annotation SummarizationSetBy = Automatic

	column SEC_TERM
		lineageTag: 5017a4d7-8de5-49a6-9cbb-96c714bfd92d
		summarizeBy: none
		isNameInferred
		sourceColumn: [SEC_TERM]

		annotation SummarizationSetBy = Automatic

	column SEC_START_DATE
		lineageTag: 5a356a92-d3f0-4a93-a22f-ce6634928a0e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SEC_START_DATE]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hours_Flag
		lineageTag: cedceac7-f3cb-4039-87e2-18da43812fc1
		summarizeBy: none
		isNameInferred
		sourceColumn: [Hours_Flag]

		annotation SummarizationSetBy = Automatic

	column Hours_Per_Week
		lineageTag: a7c85f24-1e06-4b32-a68f-a720bcf404f0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Hours_Per_Week]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Load Category' =
			
			IF(
			    ISBLANK( 'Summarize'[DateRank] ),
			    'Summarize'[Hours_Flag],
			    "# of Faculty Underload ≥ 2 Qtrs"
			)
			
			//IF('Summarize'[DateRank]=BLANK(),'Summarize'[Hours_Flag], "# Of Faculty Underload >2")
		lineageTag: 3682382d-92bd-4da2-b397-438fef413782
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Term Sort' = LOOKUPVALUE(DIM_Terms[FacultyLoadTerms], DIM_Terms[TERMS_ID], 'Summarize'[SEC_TERM])
		formatString: 0
		lineageTag: 5e579bd2-f42c-4616-b0ff-0a0f12b49871
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Load = ```
			
			IF(
			    'Summarize'[Hours_Per_Week] < 28, 
			    "Underload", 
			    IF(
			        'Summarize'[Hours_Per_Week] >= 28 && 'Summarize'[Hours_Per_Week] <= 32, 
			        "At load", 
			        IF(
			            'Summarize'[Hours_Per_Week] > 32, 
			            "Overload", 
			            BLANK()
			        )
			    )
			)
			
			```
		lineageTag: 32489d0a-1708-40b8-aac0-e91234f591e6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column WKLD_Hours
		lineageTag: e601d7ab-6c28-4429-82f4-8868c6618b2e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [WKLD_Hours]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Service_Hours
		lineageTag: bcb5b723-da76-48a1-a38e-bfba3ba4cfdb
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Service_Hours]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Contact_and_Prep_Hours
		lineageTag: 6c641798-1a91-48b9-a966-68411b577627
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Contact_and_Prep_Hours]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Contact_Hours
		lineageTag: 1e5fc283-d8ae-4792-bcae-67f47c2b2309
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Contact_Hours]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prep_Hours
		lineageTag: e94e8618-02b4-471d-bce4-5edaa86bc9dc
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Prep_Hours]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Summarize = calculated
		mode: import
		source = ```
				
				
				 
				// VAR RankedData =
				//     ADDCOLUMNS(
				//         'Faculty Load',
				//         "DateRank",
				//         RANKX(
				//             FILTER('Faculty Load', 'Faculty Load'[Colleague_ID] = EARLIER('Faculty Load'[Colleague_ID])),
				//             'Faculty Load'[SEC_START_DATE],
				//             ,
				//             ASC
				//         )
				//     )
				// VAR A =
				// SELECTCOLUMNS( FILTER(
				//     RankedData,
				//     [DateRank] > 1 && [Hours_Flag] = "# of Faculty Underload"
				// ), "Colleague_ID",'Faculty Load'[Colleague_ID],"Course", 'Faculty Load'[Course],"EMP_STATUS", 'Faculty Load'[EMP_STATUS],"Hours_Flag",'Faculty Load'[Hours_Flag],"Hours_Per_Week",'Faculty Load'[Hours_Per_Week], "FIRST_NAME", 'Faculty Load'[FIRST_NAME],"LAST_NAME", 'Faculty Load'[LAST_NAME],"SEC_TERM", 'Faculty Load'[SEC_TERM], "SEC_START_DATE",'Faculty Load'[SEC_START_DATE], [DateRank])
				
				// VAR B = SELECTCOLUMNS('Faculty Load', "Colleague_ID",'Faculty Load'[Colleague_ID],"Course", 'Faculty Load'[Course],"EMP_STATUS", 'Faculty Load'[EMP_STATUS],"Hours_Flag",'Faculty Load'[Hours_Flag],"Hours_Per_Week",'Faculty Load'[Hours_Per_Week],"FIRST_NAME", 'Faculty Load'[FIRST_NAME],"LAST_NAME", 'Faculty Load'[LAST_NAME],"SEC_TERM", 'Faculty Load'[SEC_TERM], "SEC_START_DATE",'Faculty Load'[SEC_START_DATE], "Daterank",BLANK())
				// RETURN
				// UNION(A,B)
				
				
				
				VAR CurrentTerm = MAX('Faculty Load'[SEC_TERM])
				
				VAR RankedData =
				    ADDCOLUMNS(
				        'Faculty Load',
				        "DateRank",
				        RANKX(
				            FILTER('Faculty Load', 'Faculty Load'[Colleague_ID] = EARLIER('Faculty Load'[Colleague_ID])),
				            'Faculty Load'[SEC_START_DATE],
				            ,
				            ASC
				        )
				    )
				
				VAR A =
				    SELECTCOLUMNS(
				        FILTER(
				            RankedData,
				            [DateRank] > 1 && [Hours_Flag] = "# of Faculty Underload"
				        ),
				        "Colleague_ID", 'Faculty Load'[Colleague_ID],
				        "Course", 'Faculty Load'[Course],
				        "EMP_STATUS", 'Faculty Load'[EMP_STATUS],
				        "Hours_Flag", 'Faculty Load'[Hours_Flag],
				        "Hours_Per_Week", 'Faculty Load'[Hours_Per_Week],
				        "FIRST_NAME", 'Faculty Load'[FIRST_NAME],
				        "LAST_NAME", 'Faculty Load'[LAST_NAME],
				        "SEC_TERM", 'Faculty Load'[SEC_TERM],
				        "SEC_START_DATE", 'Faculty Load'[SEC_START_DATE],
				        "DateRank", [DateRank],
				        "WKLD_Hours", 'Faculty Load'[WKLD_HOURS],
				        "Service_Hours", 'Faculty Load'[SERVICE_HOURS],
				        "Contact_and_Prep_Hours", 'Faculty Load'[CONTACT_AND_PREP_HOURS],
				        "Contact_Hours", 'Faculty Load'[CONTACT_HOURS],
				        "Prep_Hours", 'Faculty Load'[PREP_HOURS]
				    )
				
				VAR B =
				    SELECTCOLUMNS(
				        'Faculty Load',
				        "Colleague_ID", 'Faculty Load'[Colleague_ID],
				        "Course", 'Faculty Load'[Course],
				        "EMP_STATUS", 'Faculty Load'[EMP_STATUS],
				        "Hours_Flag", 'Faculty Load'[Hours_Flag],
				        "Hours_Per_Week", 'Faculty Load'[Hours_Per_Week],
				        "FIRST_NAME", 'Faculty Load'[FIRST_NAME],
				        "LAST_NAME", 'Faculty Load'[LAST_NAME],
				        "SEC_TERM", 'Faculty Load'[SEC_TERM],
				        "SEC_START_DATE", 'Faculty Load'[SEC_START_DATE],
				        "DateRank", BLANK(),
				          "WKLD_Hours", 'Faculty Load'[WKLD_HOURS],
				        "Service_Hours", 'Faculty Load'[SERVICE_HOURS],
				        "Contact_and_Prep_Hours", 'Faculty Load'[CONTACT_AND_PREP_HOURS],
				        "Contact_Hours", 'Faculty Load'[CONTACT_HOURS],
				        "Prep_Hours", 'Faculty Load'[PREP_HOURS]
				    )
				
				VAR C =
				    SELECTCOLUMNS(
				       EXCEPT(
				            SELECTCOLUMNS('Operations - HR', "Colleague_ID", 'Operations - HR'[Person_ID]),
				            SELECTCOLUMNS(FILTER('Faculty Load', 'Faculty Load'[SEC_TERM] == CurrentTerm), "Colleague_ID", 'Faculty Load'[Colleague_ID])
				        ),
				        "Colleague_ID", [Colleague_ID],  
				        "Course", BLANK(),
				        "EMP_STATUS", BLANK(),
				        "Hours_Flag", "# of Faculty Unassigned",
				        "Hours_Per_Week", BLANK(),
				        "FIRST_NAME", BLANK(),
				        "LAST_NAME", BLANK(),
				        "SEC_TERM", CurrentTerm,
				        "SEC_START_DATE", BLANK(),
				        "DateRank", BLANK(),
				          "WKLD_Hours", BLANK(),
				        "Service_Hours", BLANK(),
				        "Contact_and_Prep_Hours", BLANK(),
				        "Contact_Hours", BLANK(),
				        "Prep_Hours", BLANK()
				    )
				
				
				RETURN
				    UNION(A, B, C)
				```

	annotation PBI_Id = 05314460195a4554bffc116b0e121f9a

